### ISSUE TITLE
Config source

### ISSUE THREAD

**Issue by kiquenet** [Taritsyn/WebMarkupMin#1]
Is it possible ?

```
 < webMarkupMin >
 < core configSource="Config\webMarkupMin.core.config" / >
```

...

Like

```
< system.webServer >

< httpErrors configSource="Config\system.webServer.httpErrors.config" / >
```

**Comment by Taritsyn** [comment]
Hello, Kiquenet!

No, it is immpossible. I recommend you to read [“How to upgrade applications to version 2.X”](https://github.com/Taritsyn/WebMarkupMin/wiki/How-to-upgrade-applications-to-version-2.X) section of the documentation.

**Comment by Taritsyn** [comment]
Similar code will work in [WebMarkupMin version 1.X](http://webmarkupmin.codeplex.com/). I checked it on the test project.

But this approach has disadvantages:
1. Will not work IntelliSense.
2. This settings can be overwritten when upgrading packages.

I think it's better to upgrade WebMarkupMin to version 2.X and use an imperative approach to configuration.
