### ISSUE TITLE
Crash parsing invalid comment block

### ISSUE THREAD

**Issue by greg84** [Taritsyn/WebMarkupMin#10]
We have an invalid comment block as below (it was generated by our authoring system - the bug that caused it is being fixed!):

```
<!-->
```

It throws an ArgumentOutOfRangeException exception on [this line](https://github.com/Taritsyn/WebMarkupMin/blob/master/src/WebMarkupMin.Core/Parsers/HtmlParser.cs#L362) (Length cannot be less than zero. Parameter name: length), because the comment block is invalid and it can't find the closing `-->` sequence.

It would be nice if this markup error was ignored, perhaps by adding a check to ensure that `commentEndPosition > -1` before trying to find the comment text?

**Comment by Taritsyn** [comment]
Hello, Greg!

Thanks for information! I will fix this error in next release.

**Comment by Taritsyn** [comment]
Hello, Greg!

In WebMarkupMin [2.0.1](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.0.1) and [1.1.5](https://webmarkupmin.codeplex.com/releases/view/624978) fixed this error.
