### ISSUE TITLE
Getting issue on *.dep.json under release project 

### ISSUE THREAD

**Issue by abhishekbhalani** [Taritsyn/WebMarkupMin#103]
Error:
  An assembly specified in the application dependencies manifest (MyWeb.deps.json) was not found:
    package: 'AdvancedStringBuilder', version: '0.1.0'
    path: 'lib/netstandard2.0/AdvancedStringBuilder.dll'

Even I have copied the DLL under runtime folder under project published location..

@Taritsyn Can you share your thought on this? 
why still showing error Not found.

Thank you.

**Comment by Taritsyn** [comment]
Hello, Abhishek!

There was already a similar error - [“asp.net core 3.0 rc1 issue”](https://github.com/Taritsyn/WebMarkupMin/issues/97).

**Comment by abhishekbhalani** [comment]
Thank you.
I have put DLL file over there, even it throwing error that file not found.. 
Can I update version ?

![image](https://user-images.githubusercontent.com/1845707/71975234-4d3b9180-320b-11ea-9736-876e7c9edc2b.png)

**Comment by Taritsyn** [comment]
`AdvancedStringBuilder.dll` assembly must be located in the `\bin\Release\netcoreappX.X` directory. This assembly should not be in the `runtimes` directory, because it is not platform dependent.

**Comment by abhishekbhalani** [comment]
Ok.. 
Let me try to remove from runtime json file..

**Comment by abhishekbhalani** [comment]
@Taritsyn On publish version there has not bin or release folder.
I also removed **runtime** section from the <site>dep.json file.

Finally I only intake compile json key only as below..
 
![image](https://user-images.githubusercontent.com/1845707/71980699-a1993e00-3218-11ea-8661-236a2a1c00a4.png)

**Comment by abhishekbhalani** [comment]
> `AdvancedStringBuilder.dll` assembly must be located in the `\bin\Release\netcoreappX.X` directory. This assembly should not be in the `runtimes` directory, because it is not platform dependent.

On development code its working,
Mainly issue coming while deployed with release mode.. 
on server there has no any bin or release .. published with the portable mode..

**Comment by abhishekbhalani** [comment]
I have published with the win64 mode then after it is working. 
but on portable (framework dependent ) mode not working.
