### ISSUE TITLE
V2.8.2 blank page , can not working with comment in inline style html 

### ISSUE THREAD

**Issue by HashemGo** [Taritsyn/WebMarkupMin#106]
Hi, Thank You for this a great work, please keep going

fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
WebMarkupMin.Core.MarkupMinificationException: Category: CSS_MINIFICATION_ERROR
Message: Unterminated comment.
File: /
Line number: 190
Column number: 194
Source fragment:
Line 189: 
Line 190: …5202b;border: 1px solid #243444;/*! height: 85%;"></div>

**Comment by Taritsyn** [comment]
Hello, Hashem!

This is a parsing error. Your inline CSS code contains an unclosed multiline comment:

```css
/*! height: 85%;
```

Just close this comment.

**Comment by HashemGo** [comment]
thank you, its working now
i wish if this error show up in visual studio or in browser  
It only shows a empty page.

**Comment by Taritsyn** [comment]
Use a `ThrowExceptionLogger`.
