### ISSUE TITLE
Compression JS and Css files 

### ISSUE THREAD

**Issue by rw-nowakpiotr** [Taritsyn/WebMarkupMin#108]
I created a sample application  - ASP.NET 5.2. Next i added WebMarkupMinConfig.cs and then I register it in RegisterGlobalFilters.cs. I suppose this should compress all content e.g. html, js, css files and so on. The network tab observes that only html files have "content-encoding: br", while js and css files do not have.  Is it possible to compress JS and Css files ?
`public class WebMarkupMinConfig
	{
		public static void Configure(WebMarkupMinConfiguration configuration)
		{
			configuration.AllowMinificationInDebugMode = true;
			configuration.AllowCompressionInDebugMode = true;
			configuration.DisablePoweredByHttpHeaders = true;

			DefaultLogger.Current = new ThrowExceptionLogger();
			DefaultCssMinifierFactory.Current = new MsAjaxCssMinifierFactory();
			DefaultJsMinifierFactory.Current = new MsAjaxJsMinifierFactory();

			IHtmlMinificationManager htmlMinificationManager = HtmlMinificationManager.Current;
			htmlMinificationManager.IncludedPages.Add(new WildcardUrlMatcher("*"));
			HtmlMinificationSettings htmlMinificationSettings = htmlMinificationManager.MinificationSettings;
			htmlMinificationSettings.RemoveRedundantAttributes = true;
			htmlMinificationSettings.RemoveHttpProtocolFromAttributes = true;
			htmlMinificationSettings.RemoveHttpsProtocolFromAttributes = true;

			IXhtmlMinificationManager xhtmlMinificationManager = XhtmlMinificationManager.Current;
			XhtmlMinificationSettings xhtmlMinificationSettings = xhtmlMinificationManager.MinificationSettings;
			xhtmlMinificationSettings.RemoveRedundantAttributes = true;
			xhtmlMinificationSettings.RemoveHttpProtocolFromAttributes = true;
			xhtmlMinificationSettings.RemoveHttpsProtocolFromAttributes = true;

			IXmlMinificationManager xmlMinificationManager = XmlMinificationManager.Current;
			XmlMinificationSettings xmlMinificationSettings = xmlMinificationManager.MinificationSettings;
			xmlMinificationSettings.CollapseTagsWithoutContent = true;

			IHttpCompressionManager httpCompressionManager = HttpCompressionManager.Current;

		    httpCompressionManager.SupportedMediaTypePredicate = str => true; ;

			httpCompressionManager.CompressorFactories = new List<ICompressorFactory> 
			{
				new BrotliCompressorFactory(new BrotliCompressionSettings
				{
					Level = 2
				}),
				new DeflateCompressorFactory(),
				new GZipCompressorFactory()
			};
		}
	}`

`public class FilterConfig
    {
        public static void RegisterGlobalFilters(GlobalFilterCollection filters)
        {
            filters.Add(new HandleErrorAttribute());
            filters.Add(new CompressContentAttribute());
            filters.Add(new MinifyHtmlAttribute());
        }
    }`

**Comment by Taritsyn** [comment]
> I suppose this should compress all content e.g. html, js, css files and so on. The network tab observes that only html files have "content-encoding: br", while js and css files do not have.

Action filters can only process the results of controller actions. This is a limitation of ASP.NET MVC framework.

> Is it possible to compress JS and Css files ?

If you want to process all kinds of assets, then use the [WebMarkupMin.AspNet4.HttpModules](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-4.X-HTTP-modules) module instead of the [WebMarkupMin.AspNet4.Mvc](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-4.X-MVC) module.

**Comment by CumpsD** [comment]
@Taritsyn related question, what is the ASP.NET Core module to use if you want to compress JS/CSS?

----
Nevermind, I had StaticFiles before...

**Comment by Taritsyn** [comment]
Hello, David!

To compress separated JS and CSS files, use the following setting:

```csharp
public class Startup
{
    …
    // This method gets called by the runtime.
    // Use this method to add services to the container.
    public void ConfigureServices(IServiceCollection services)
    {
        …
        // Add WebMarkupMin services.
        services.AddWebMarkupMin()
            …
            .AddHttpCompression()
            ;

        // Add framework services.
        services.AddMvc();
        …
    }

    // This method gets called by the runtime.
    // Use this method to configure the HTTP request pipeline.
    public void Configure(IApplicationBuilder app, IHostingEnvironment env,
        ILoggerFactory loggerFactory)
    {
        …
        app.UseWebMarkupMin();
        …
        app.UseStaticFiles();
        …
        app.UseMvc(routes =>
        {
            …
        });
    }
}
```
You can use the `SupportedMediaTypePredicate` property of `HttpCompressionOptions` class to fine-tune the supported media-types. 

WebMarkupMin does not support minification of separated JS and CSS files. For these purposes, I recommend that you try the [Smidge](https://github.com/Shazwazza/Smidge) library.

**Comment by CumpsD** [comment]
@Taritsyn thanks, I had that, but had UseStaticFiles in the wrong place, it's working now.

Using uglify-js for the modification of js and sass for css
