### ISSUE TITLE
Minify is removing HTML tags

### ISSUE THREAD

**Issue by tmeschede** [Taritsyn/WebMarkupMin#109]
The Minify function is removing </body> and </html> tags.  I have not gone through the whole document as of yet, but I figured I would report the issue of what I have seen so far.

I will attach examples.

If you go to the very end of the file named CustomerSession_637251461300286330.txt .. you will see the </body> and </html> tags.  This is how the HTML looks prior to Minify function.

File Min_CustomerSession_637251461300286330.txt is the result of Minify function.  You will see the tags missing.  Hopefully these are the only ones, but if I find more I will let you know.

Tom
[Min_CustomerSession_637251461300286330.txt](https://github.com/Taritsyn/WebMarkupMin/files/4636313/Min_CustomerSession_637251461300286330.txt)
[CustomerSession_637251461300286330.txt](https://github.com/Taritsyn/WebMarkupMin/files/4636328/CustomerSession_637251461300286330.txt)

**Comment by tmeschede** [comment]
For some reason the text box removed my "</body>" and "</html>" tags from my write up.

I will re-attach it:

The Minify function is removing "</body>" and "</html>" tags. I have not gone through the whole document as of yet, but I figured I would report the issue of what I have seen so far.

I will attach examples.

If you go to the very end of the file named CustomerSession_637251461300286330.txt .. you will see the "</body>" and "</html>" tags. This is how the HTML looks prior to Minify function.

File Min_CustomerSession_637251461300286330.txt is the result of Minify function. You will see the tags missing. Hopefully these are the only ones, but if I find more I will let you know.

**Comment by Taritsyn** [comment]
Hello!

Removing of optional end tags is allowed by HTML standard (see the [“8.1.2.4. Optional tags”](https://www.w3.org/TR/html52/syntax.html#optional-tags) paragraph).

You can disable this setting if you set a `false` to the `RemoveOptionalEndTags` property (see the [“HTML Minifier”](https://github.com/Taritsyn/WebMarkupMin/wiki/HTML-Minifier) section of documentation).

**Comment by tmeschede** [comment]
OK .. I am attaching issue.
[Min_Error_Issue.txt](https://github.com/Taritsyn/WebMarkupMin/files/4636444/Min_Error_Issue.txt)

**Comment by Taritsyn** [comment]
Read my previous message. I also recommend that you familiarize yourself with theory of [HTML minification](https://github.com/Taritsyn/WebMarkupMin/wiki/Additional-reading-and-resources).

**Comment by tmeschede** [comment]
Thank You for the quick response.  Appreciate it!!
