### ISSUE TITLE
MinifyHtmlAttribute doesn't minify <script type="text/html">

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Taritsyn/WebMarkupMin#11]
### Bug report

_Expected behavior_: HTML contents of scripts of type `text/html` should be minified.

_Actual behavior_: No minification happens.

As per the [HTML5 spec](https://www.w3.org/TR/html5/scripting-1.html#the-script-element), it's valid to have `"text/html"` as a script tag's content.

> The type attribute gives the language of the script or format of the data. If the attribute is present, its value must be a valid [MIME type](https://www.w3.org/TR/html5/infrastructure.html#valid-mime-type). The charset parameter must not be specified. The default, which is used if the attribute is absent, is "text/javascript".

This is used in some sites, such as [sway.com](https://sway.com/rainier) (search for `type="text/html">` in the source).

**Comment by Taritsyn** [comment]
Hello, Joshua!

Set to `ProcessableScriptTypeList` property the value equal to `"text/html"` (see [“HTML Minifier”](https://github.com/Taritsyn/WebMarkupMin/wiki/HTML-Minifier) section of the documentation).

**Comment by JoshuaKGoldberg** [comment]
Thanks for the info! I'll close this and file a new issue for a more specific use case if necessary.
