### ISSUE TITLE
did not work on some pages.

### ISSUE THREAD

**Issue by servety** [Taritsyn/WebMarkupMin#110]
Hello. I have the application in .core 3.1 version. Some pages do not minify at all. How can I see when there is an error.
 services.AddRazorPages(). AddRazorRuntimeCompilation(); 
I run the site with this parameter
could the problem be this?
Thank you for your work.

**Comment by Taritsyn** [comment]
Hello!

Show me the source code of `Configure` method from the `Startup.cs` file.

**Comment by servety** [comment]
configure in  startup.cs
 app.UseAuthorization();
            app.UseWebMarkupMin();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
                endpoints.MapRazorPages();
            });

configureservices in startup.cs

  services.AddWebMarkupMin(options =>
             {
                 options.AllowMinificationInDevelopmentEnvironment = true;
                 options.AllowCompressionInDevelopmentEnvironment = true;
             }).AddHtmlMinification()
               .AddXmlMinification()
               .AddHttpCompression().AddXhtmlMinification();


            services.AddRazorPages(). AddRazorRuntimeCompilation();


how can i catch errors
Thank you very much for your interest


i solved one page error:
**previous:**
   <div class="col-lg-4">
             <a href="#" class="btn btn-primary btn-sm" onclick=AddEditPopup('-1') >Create New Record</a>
         </div>
**fixed:**
 <div class="col-lg-4">
             <a href="#" class="btn btn-primary btn-sm" onclick="AddEditPopup('-1')" >Create New Record</a>
         </div>

**Comment by servety** [comment]
sorry i can't past html code 
 
```
previous:
             <a href="#" class="btn btn-primary btn-sm" onclick=AddEditPopup('-1') >Create New Record</a>

fixed:
 
              <a href="#" class="btn btn-primary btn-sm" onclick="AddEditPopup('-1')" >Create New Record</a>
```

**Comment by servety** [comment]
I solved same mistakes.
All pages minified now.
your product works fine.
thanks

**Comment by Taritsyn** [comment]
> how can i catch errors

In the `Startup.cs` file set a `ThrowExceptionLogger` as the default logger in order to see parsing errors:

```csharp
…
using IWmmLogger = WebMarkupMin.Core.Loggers.ILogger;
using WmmThrowExceptionLogger = WebMarkupMin.Core.Loggers.ThrowExceptionLogger;

namespace WebMarkupMin.Sample.AspNetCore3.Mvc3
{
    public class Startup
    {
        …
        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            …
            // Override the default logger for WebMarkupMin.
            services.AddSingleton<IWmmLogger, WmmThrowExceptionLogger>();
            …
        }
        …
    }
}
```

In the future I recommend to you using own implementation of logger (see the [“Loggers”](https://github.com/Taritsyn/WebMarkupMin/wiki/Loggers) section of documentation) instead of the `ThrowExceptionLogger`.
