### ISSUE TITLE
Using MiniProfiler with Html Minification Does Not Work

### ISSUE THREAD

**Issue by toddca** [Taritsyn/WebMarkupMin#112]
Repro
1. Enable AspNetCore 3.1 Site for WebMarkupWin and verify it works.
2. Configure web app to use MiniProfiler
3. In _layout.cshtml add the following:
`<mini-profiler/>`
4. Make request and notice error page returned.

MarkupMinificationException: Category: HTML_PARSING_ERROR
Message: In the start tag <script> found invalid characters.
File: /testimonial/new
Line number: 173
Column number: 338
Source fragment:

Line 172:
Line 173: …6b-4cfd-885b-04c7fa94bac0" data-position="Left"" data-scheme="Light" data-authorized="true" d…
----------------------------------------------------------^

The script tag in question looks like:
`<script async id="mini-profiler" src="/mini-profiler-resources/includes.min.js?v=4.2.1+b27bea37e9" data-version="4.2.1+b27bea37e9" data-path="/mini-profiler-resources/" data-current-id="20d30b65-6027-4d6f-87f9-3b246a9bc746" data-ids="20d30b65-6027-4d6f-87f9-3b246a9bc746" data-position="Left"" data-scheme="Light" data-authorized="true" data-max-traces="15" data-toggle-shortcut="Alt+P" data-trivial-milliseconds="2.0" data-ignored-duplicate-execute-types="Open,OpenAsync,Close,CloseAsync"></script>`

**Comment by Taritsyn** [comment]
Hello, Todd!

There is a syntax error in HTML code (extra double quote):

```
Line 1: …27-4d6f-87f9-3b246a9bc746" data-position="Left"" data-scheme="Light" data-authorized="true" d…
--------------------------------------------------------^
```

Report the error to the authors of MiniProfiler to fix it.
