### ISSUE TITLE
Problem with the content of the html attributes

### ISSUE THREAD

**Issue by germanyesid** [Taritsyn/WebMarkupMin#113]
I am having trouble minifying a page that contains the following code:

`<img alt="Vínculo al registro detallado" id="hover_1151553"  class="item-image defer-image|http://www.example.com/rpsweb/othumb?id=NL$1151553$PDF&s=e" data-dialog='{"isHover":true,"isShowVerticalPopups":true,"container":"#hover","url":"Carousel/Hover","dialogClass":"epdialog preview-hoverdialog","width":340,"data":{"title":"Ecografía en medicina intensiva","author":"Lumb, Philip D.","publisher":"Elsevier","isebook":true,"isabook":false,"iteman":"1151553","itemdb":"nlebk","itemtag":"AN","itemdoid":"NL$1151553$PDF","hoverid":"hover_1151553","downloadable":true}}' />`

When minifying it replaces some characters, for example the character "|" by " ", from the content of the attribute "class"

`<img alt="Vínculo al registro detallado" id=hover_1151786 class="item-image defer-image http://www.example.com/rpsweb/othumb?id=NL$1151786$PDF&amp;s=e" data-dialog="{&#34;isHover&#34;:true,&#34;isShowVerticalPopups&#34;:true,&#34;container&#34;:&#34;#hover&#34;,&#34;url&#34;:&#34;Carousel/Hover&#34;,&#34;dialogClass&#34;:&#34;epdialog preview-hoverdialog&#34;,&#34;width&#34;:340,&#34;data&#34;:{&#34;title&#34;:&#34;Stevens y Lowe. Histología humana + StudentConsult&#34;,&#34;author&#34;:&#34;Lowe, J. S.&#34;,&#34;publisher&#34;:&#34;Elsevier&#34;,&#34;isebook&#34;:true,&#34;isabook&#34;:false,&#34;iteman&#34;:&#34;1151786&#34;,&#34;itemdb&#34;:&#34;nlebk&#34;,&#34;itemtag&#34;:&#34;AN&#34;,&#34;itemdoid&#34;:&#34;NL$1151786$PDF&#34;,&#34;hoverid&#34;:&#34;hover_1151786&#34;,&#34;downloadable&#34;:true}}"> `

The settings currently are as follows:
                  
```
HtmlMinificationSettings settings = options.MinificationSettings;
settings.RemoveRedundantAttributes = true;
 settings.RemoveHttpProtocolFromAttributes = false;
 settings.RemoveHttpsProtocolFromAttributes = false;
 settings.RemoveHtmlComments = false;
options.CssMinifierFactory = new NUglifyCssMinifierFactory();
 options.JsMinifierFactory = new CrockfordJsMinifierFactory();

```

**Comment by Taritsyn** [comment]
Hello, German!

Thanks for information! I will try to solve this problem in the next few days.

**Comment by Taritsyn** [comment]
This error is fixed in [version 2.8.5](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.8.5).

**Comment by germanyesid** [comment]
@Taritsyn  Thank you very much, I have updated it and it works fine.

**Comment by germanyesid** [comment]
Hello @Taritsyn 

Although the error has been fixed, in some pages the processing takes a long time, after these changes.

I share with you a page which before the changes only took milliseconds to process, but now it takes between 20 and 30 seconds!.

[Example.txt](https://github.com/Taritsyn/WebMarkupMin/files/4859482/Example.txt)

**Comment by Taritsyn** [comment]
In [version 2.8.6](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.8.6), I improved a performance of the class directive processing.
