### ISSUE TITLE
meta tag content replace & with &amp;

### ISSUE THREAD

**Issue by FlorinParaschivescu** [Taritsyn/WebMarkupMin#114]
Hello,

In a meta tag I need to write an url that has & in it.
`<meta content="http://sitename.com?resize_img=true&crop=true" />`

However when the minification is on it replace the & with `&amp;` It's there a way for me to avoid this ?
`<meta content="http://sitename.com?resize_img=true&amp;crop=true" />`

I've also used this http://webmarkupmin.apphb.com/minifiers/html-minifier and it's the same.

Cheers!

**Comment by Taritsyn** [comment]
Hello, Florin!

This problem has already been discussed in the [“Why HTML minimizer encode & to &amp; ?”](https://github.com/Taritsyn/WebMarkupMin/issues/69) issue.

While the solution to this problem is delayed to third version.

**Comment by FlorinParaschivescu** [comment]
I see, thanks for your quick response!

All the best!
