### ISSUE TITLE
Minification of html class attributes with slashes

### ISSUE THREAD

**Issue by tylerfe** [Taritsyn/WebMarkupMin#115]
Hello,

I'm using WebMarkupMin.AspNetCore3 2.8.4 along with tailwindcss, and when enabling the html minification it will sometimes replace the slashes used with some of the css class names.

For example, un-minified:
`class="fixed z-40 inset-y-0 left-0 w-3/4 sm:w-1/2 md:w-2/5 lg:w-1/3 xl:w-1/4"`

When minified:
`class="fixed z-40 inset-y-0 left-0 w-3 4 sm:w-1/2 md:w-2/5 lg:w-1/3 xl:w-1/4"`

The `w-3/4` in the class attribute is minified to `w-3 4`. This doesn't seem to effect the other classes that are prefixed by the screen size though (like sm:, md:, etc.).

**Comment by Taritsyn** [comment]
Hello!

Update the [WebMarkupMin.Core](https://www.nuget.org/packages/WebMarkupMin.Core/) package to version 2.8.6. If this package is not in the list of dependencies, then install it.

**Comment by tylerfe** [comment]
Thanks for the quick reply! 

That fixed the issue - thanks!
