### ISSUE TITLE
ASP.NET Core 3.1.6

### ISSUE THREAD

**Issue by armin-gitter** [Taritsyn/WebMarkupMin#116]
Hello, Thanks for this nice package.
please update [WebMarkupMin.AspNetCore3 ](https://www.nuget.org/packages/WebMarkupMin.AspNetCore3/) for supporting ASP.NET Core 3.1.6  SDK 3.1.302

**Comment by Taritsyn** [comment]
Hello, Armin!

This problem is resolved in [version 2.8.8](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.8.8).
