### ISSUE TITLE
HTTP modules cause forms button do post back error

### ISSUE THREAD

**Issue by kenyazilim** [Taritsyn/WebMarkupMin#12]
When HTTP modules HtmlMinificationModule used asp.net butons do post back not working. I think it's removing some codes.

The javaScript conseole gives "WebForm_DoPostBackWithOptions is not defined" error.

**Comment by Taritsyn** [comment]
Hello, Adalilar!

I could not reproduce this error.

Try to reproduce this error in the form of a small demonstration project, and then send me a link to its source code.

**Comment by kenyazilim** [comment]
Hello!

If you need I can create a demo live page.

**test.aspx**
`<form id="form1" runat="server">
    <asp:TextBox ID="inputKeywords" name="inputKeywords" value="" runat="server" required="required" MaxLength="255"></asp:TextBox>
    <asp:Button ID="Button1" runat="server" Text=" Apply " />
</form>`

**test.aspx.cs**
`var id = "5";
Button1.PostBackUrl = "test.aspx?do=add&id=" + id;`

Offcouser we need to install and enable HTTP modules

**Nuget Console**
`
Install-Package WebMarkupMin.AspNet4.HttpModules
`

**Web.config**
`
<system.webServer>
    <modules>
      
      
      <add name="HtmlMinificationModule" type="WebMarkupMin.AspNet4.HttpModules.HtmlMinificationModule, WebMarkupMin.AspNet4.HttpModules" />
      <add name="HttpCompressionModule" type="WebMarkupMin.AspNet4.HttpModules.HttpCompressionModule, WebMarkupMin.AspNet4.HttpModules" />
            
    </modules>
</system.webServer>
`

When you try to run this code the button do not working. It's sending data to current url not to post back url. And if you se javascript console (easy way click button when text box emty) it will give "WebForm_DoPostBackWithOptions is not defined" error.

**Comment by Taritsyn** [comment]
In [WebMarkupMin 2.1.1](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.1.1) fixed this error.

Thanks for information!

Problem has been found in `HttpCompressionModule`. It turned out, that in ASP.NET Web Forms can not correctly apply HTTP compression to `WebResource.axd` file. Therefore I excluded this file from processing.
