### ISSUE TITLE
<script> tag with type="text/template" is not minified and the library throws an exception when such tag is malformed

### ISSUE THREAD

**Issue by mariannk** [Taritsyn/WebMarkupMin#121]
Please the stack trace:
![Stack trace](http://dl3.joxi.net/drive/2020/09/30/0015/3873/1011489/89/d8c84557ce.jpg)

**Comment by Taritsyn** [comment]
Hello, Mariann!

Stack trace shows that this error occurred during minification of JS code by using the [NUglify](https://github.com/trullock/NUglify) library. But the main oddity is that content of the `script` tag with `type="text/template"` is never processed as JS code. By default, content of such tags is not processed at all, and if the `text/template` content type is specified in the `ProcessableScriptTypeList` property, it is processed as HTML code (you can check this by using the [WebMarkupMin Online](http://webmarkupmin.apphb.com/minifiers/html-minifier)).

To understand real reasons for this error, I need to see the original HTML code.

**Comment by mariannk** [comment]
Hi, Andrey!

The part of the code I had this issue with is [here](https://github.com/nopSolutions/nopCommerce/blob/256b34caa8f0263e49de995c3d84efa0f59683dd/src/Presentation/Nop.Web/Areas/Admin/Views/Shared/EditorTemplates/Picture.cshtml#L51)

It actually is not such a big issue for us at the moment but the problem is that if you customize this code and accidentally make a mistake you will see an exception and then never guess where the problem is using the stack trace.

**Comment by Taritsyn** [comment]
Hello, Mariann!

Example code you provided is a Razor-template, and I need the output HTML code.

Also noticed that your project (see the [`Nop.Web.Framework.csproj`](https://github.com/nopSolutions/nopCommerce/blob/92e57d7a37490773cc21b83a0bb3c57cad6f92ce/src/Presentation/Nop.Web.Framework/Nop.Web.Framework.csproj#L19-L20) file) is using a fairly old version of the WebMarkupMin's packages:
```xml
  …
  <ItemGroup>
    …
    <PackageReference Include="WebMarkupMin.AspNetCore3" Version="2.8.2" />
    <PackageReference Include="WebMarkupMin.NUglify" Version="2.8.1" />
  </ItemGroup>
  …
```
It is possible that if you update the packages, this error may disappear by itself.
