### ISSUE TITLE
Release aspnetcore5 module to Nuget/.net5 support

### ISSUE THREAD

**Issue by cjblomqvist** [Taritsyn/WebMarkupMin#122]
Hi! I see you've added a aspnetcore5 module - but I can't find it on NuGet. Is it ready to be used? In such case, could you publish it to nuget?

Thanks for your nice lib!

**Comment by Taritsyn** [comment]
Hello!

I am currently conducting some experiments with increasing the performance of regular expressions (I didn’t use the `RegexOptions.Compiled` flag before, because it led to a serious drop in performance at the start of applications). Because of this, release for .NET 5 is delayed.

**Comment by cjblomqvist** [comment]
Thanks for quick reply!

Do you know if latest aspnetcore3 version is .net5 compatible? Otherwise it might be wise to release a first version of aspnetcore5 that works, and then release another with the enhanced regular expression performance.

**Comment by Taritsyn** [comment]
> Do you know if latest aspnetcore3 version is .net5 compatible?

Oddly enough, the WebMarkupMin.AspNetCore3 module is fully compatible with ASP.NET Core 5.0. ASP.NET Core 5.0 is first of major versions that is backward compatible with previous version.

I am creating the WebMarkupMin.AspNetCore5 module just to improve performance.

**Comment by Taritsyn** [comment]
Hello!

[WebMarkupMin.AspNetCore5](https://www.nuget.org/packages/WebMarkupMin.AspNetCore5/) package was published in [version 2.9.0](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.9.0).
