### ISSUE TITLE
Hangfire dashboard and related pages won't load when using WebMarkupMin

### ISSUE THREAD

**Issue by J3-code** [Taritsyn/WebMarkupMin#123]
I'm struggling to get the Hangfire dashboard and related pages to work when minification and compression is enabled. When enabled, the dashboard url simply returns a **;**

[This Hangfire issue](https://github.com/HangfireIO/Hangfire/issues/1350) indicates that someone was able to get the dashboard to render by excluding Hangfire URL from minification and compression. Here's my attempt at that:

```
var excludedUrls = new List<IUrlMatcher>
{
	new ExactUrlMatcher("/hangfire"),
	new ExactUrlMatcher("/hangfire/"),
	new RegexUrlMatcher(@"^\/hangfire\/.+$")
};

services.AddWebMarkupMin(options =>
{
	options.AllowMinificationInDevelopmentEnvironment = true;
	options.AllowCompressionInDevelopmentEnvironment = true;
}).AddHtmlMinification(options =>
{
	HtmlMinificationSettings settings = options.MinificationSettings;
	settings.RemoveHttpProtocolFromAttributes = true;
	settings.RemoveHttpsProtocolFromAttributes = true;
	settings.RemoveHtmlComments = true;
	settings.RemoveHtmlCommentsFromScriptsAndStyles = true;
	settings.RemoveJsTypeAttributes = true;
	settings.RemoveOptionalEndTags = true;

	options.CssMinifierFactory = new NUglifyCssMinifierFactory();
	options.JsMinifierFactory = new NUglifyJsMinifierFactory();
	options.ExcludedPages = excludedUrls;
}).AddHttpCompression(options =>
{
	options.ExcludedPages = excludedUrls;
	options.CompressorFactories = new List<ICompressorFactory>
	{
		new BrotliCompressorFactory(new BrotliCompressionSettings { Level = 1 }),
		new DeflateCompressorFactory(new DeflateCompressionSettings { Level = CompressionLevel.Fastest }),
		new GZipCompressorFactory(new GZipCompressionSettings { Level = CompressionLevel.Fastest })
	};
});
```

The code above results in an error on the dashboard instead of a **;**

> ### ArgumentException: Value cannot be empty. (Parameter 'url')
> WebMarkupMin.AspNet.Common.UrlMatchers.ExactUrlMatcher.IsMatch(string url)

All other hangfire-related pages, such as /hangfire/retries result in a **;**

Am I doing something wrong when attempting to exclude hangfire-related URLs from processing?

**Comment by Taritsyn** [comment]
Hello, James!

This line of code is definitely redundant:

```csharp
	new ExactUrlMatcher("/hangfire/"),
```

**Comment by J3-code** [comment]
You're correct! I mean to take that out before I posted. I was testing several scenarios. Same net effect with it gone.

**Comment by Taritsyn** [comment]
Which version ASP.NET Core what do you use?

**Comment by J3-code** [comment]
I'm using .Net 5. and WebMarkupMin.AspNetCore5 (2.9.0). I should have included that in my original post - apologies!

**Comment by Taritsyn** [comment]
Try to reproduce this error in the form of demo project and send me a link to it.

**Comment by Taritsyn** [comment]
Hello, James!

In [version 2.9.1](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.9.1), I only fixed an error that occurs in the URL matchers, i.e. now you can exclude the Hangfire dashboard and related pages from processing without any problems. This error was caused by the Hangfire's author storing part of the enddpoint URL in the `PathBase` property of `HttpRequest` class. 

Basically, you initially had the option to disable the WebMarkupMin for the Hangfire dashboard. It was just necessary to change the order of calling the middlewares:

```csharp
        …
        public void Configure(IApplicationBuilder app, IBackgroundJobClient backgroundJobs, IWebHostEnvironment env)
        {
            …
            app.UseHangfireDashboard();
            backgroundJobs.Enqueue(() => Console.WriteLine("Hello world from Hangfire!"));

            app.UseWebMarkupMin();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
                endpoints.MapHangfireDashboard();
            });
        }
    }
}
```

The bad news is that the WebMarkupMin is still incompatible with the Hangfire. This is because the Hangfire dashboard always returns read-only HTTP headers.

In addition, there remains a problem related to the display of blank pages when exceptions are thrown in the WebMarkupMin middleware. I have been seeing this problem since the release of ASP.NET Core 3.1. Unfortunately, I haven't figured out how to solve it yet.

**Comment by J3-code** [comment]
Hi, Taritsyn! Thanks so much for looking into this even before I was able to get a test project set up for you. It's much appreciated!

It sounds like I need to present the issues that you uncovered to Hangfire. I'd love for you guys to be able to co-exist.

Thanks again!

EDIT: I misunderstood your original response and I see now, after  updating to 2.9.1 that the Hangfire dashboard is working (after excluding from minification). Again, your work is appreciated 👍
