### ISSUE TITLE
removing </link> tags on xml

### ISSUE THREAD

**Issue by komplika** [Taritsyn/WebMarkupMin#124]
Hi

i'm using for .net core 5 website and generate xml files.
it's removing close </link> tag in xml

`<rss xmlns:g="http://base.google.com/ns/1.0" version="2.0">
	<channel>
		<title>xxx.com Products</title>
		<link>https://xxx.com <description>xxx.com facebook pixel products</description>`

**Comment by Taritsyn** [comment]
Hello!

What minifier are you using? From description of the error, it looks like you are using an HTML minifier to minify a XML code.

**Comment by komplika** [comment]
Hi,

 

WebMarkupMin.Core and WebMarkupMin.AspNetCore5.

 

Generating a facebook xml from website.

 

Html minification Works perfectly. But xml it don’t.

**Comment by Taritsyn** [comment]
> Generating a facebook xml from website.

Under what a `Content-Type` HTTP header is this document returned?

**Comment by komplika** [comment]
Hi,

 

Content-type xml

**Comment by Taritsyn** [comment]
> Content-type xml

This is an invalid content type.

Show me your WebMarkupMin settings from the `Startup.cs` file.

**Comment by komplika** [comment]
it's resolved for adding to content-type th document
HttpContext.Response.ContentType = "application/xml";
