### ISSUE TITLE
System.NullReferenceException in middleware

### ISSUE THREAD

**Issue by zlatkolakisic** [Taritsyn/WebMarkupMin#125]
Ok, so I am trying to integrate WebMarkupMin.AspNetCore2@2.9.1 into our project to minify our markup output.

I ran into this exception when doing the standard integration as per: [https://andrewlock.net/html-minification-using-webmarkupmin-in-asp-net-core/](https://andrewlock.net/html-minification-using-webmarkupmin-in-asp-net-core/)

The exception details are
`System.NullReferenceException: Object reference not set to an instance of an object.
   at WebMarkupMin.AspNetCore2.BodyWrapperStreamBase.InternalFinishAsync() in E:\WebMarkupMin-master\src\WebMarkupMin.AspNetCore1\BodyWrapperStreamBase.cs:line 336
   at WebMarkupMin.AspNetCore2.BodyWrapperStreamWithBufferingFeature.FinishAsync() in E:\WebMarkupMin-master\src\WebMarkupMin.AspNetCore1\BodyWrapperStreamWithBufferingFeature.cs:line 51
   at WebMarkupMin.AspNetCore2.WebMarkupMinMiddleware.ProcessAsync(HttpContext context, Boolean useMinification, Boolean useCompression) in E:\WebMarkupMin-master\src\WebMarkupMin.AspNetCore1\WebMarkupMinMiddleware.cs:line 56
   at WebMarkupMin.AspNetCore2.WebMarkupMinMiddlewareBase.Invoke(HttpContext context) in E:\WebMarkupMin-master\src\WebMarkupMin.AspNetCore1\WebMarkupMinMiddlewareBase.cs:line 118
   at MD.CMS.Administration.Core.Startup.<>c.<<Configure>b__13_0>d.MoveNext() in E:\Projects\cms\MD.CMS.Administration\MD.CMS.Administration.Core\Startup.cs:line 155
--- End of stack trace from previous location where exception was thrown ---`

I went ahead and downloaded the source code, compiled a debug enable version, and dropped it into the project. After running through the process I noticed the null reference happens in the BodyWrapperStreamBase class on line 336 because _cachedStream is null. Upon further investigation, I found that the Dispose method is being called before this InternalFinishAsync method. Can you shed some light on why this is happening?

Any help is greatly appreciated!

Zlatko

**Comment by Taritsyn** [comment]
Hello, Zlatko!

Which version of ASP.NET Core do you use?

**Comment by Taritsyn** [comment]
I must say right away that sometimes some third-party libraries can lead to errors in the WebMarkupMin middleware. For example, previously there were [errors when working with the Hangfire](https://github.com/Taritsyn/WebMarkupMin/issues/123).

**Comment by zlatkolakisic** [comment]
Hi, thanks for that. So I have literally removed **all** other middleware that was registered and am still getting the same error...

This is my Configure method now:
`public virtual void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            AdminAddonAppBuilder.Default.AdminSystemTitle = Properties.Resources.MDCMSAdministrationTitle;

            _appBuilder = new AdminAddonAppBuilder(app);

            if (!MD.CMS.BusinessLogic.Core.Properties.Settings.Default.ProductionMode)
            {
                app.UseDeveloperExceptionPage();
            }

            _appBuilder.ApplicationBuilder.UseStaticFiles();

            _appBuilder.ApplicationBuilder.UseWebMarkupMin();

            _appBuilder.ApplicationBuilder.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}");
            });
        }`

**Comment by Taritsyn** [comment]
```
_appBuilder = new AdminAddonAppBuilder(app);
```

Any specific settings can be made in this line.

**Comment by zlatkolakisic** [comment]
Hi @Taritsyn 

Thanks for the reply, here is the constructor for that class:

`public AdminAddonAppBuilder(IApplicationBuilder app)
        {
            _applicationBuilder = app;
        }`

**Comment by Taritsyn** [comment]
You can try to make a standard ASP.NET Core application and, most likely, everything will work in it. Problems can arise from the specifics of CMS implementation.

Usually, developers create for CMS a plugins that use the WebMarkupMin.Core module directly.

**Comment by zlatkolakisic** [comment]
So through digging around I found the culprit, a service that inherited the IHttpResponseStreamWriterFactory. Just for future reference, this can cause this issue.

Note, this could be a good place to add some null reference checking, log a warning maybe and allow the application to proceed without minification.

Thanks for your help!

**Comment by Taritsyn** [comment]
> ... and allow the application to proceed without minification.

This is impossible in principle, because if the `_cachedStream` field on line 336 is null, then it means that all markup output is already lost.
