### ISSUE TITLE
WebMarkupMin removes </br>

### ISSUE THREAD

**Issue by kaushambi2612** [Taritsyn/WebMarkupMin#126]
<'br> or <'br/> doesn't get removed. ✔
<'/br> gets removed from the html. ❌

I understand that <'/br> is not the suggested way of adding a line-break. But, I'd like to know which setting would help me **prevent the removal of this.** 

Till now, I have used: 
options.MinificationSettings.PreservableOptionalTagList = "br";
options.MinificationSettings.RemoveOptionalEndTags = false;

[added a ' to prevent github from using the tags]

**Comment by Taritsyn** [comment]
Hello, Kaushambi!

> …, I'd like to know which setting would help me prevent the removal of this.

This setting does not exist, but you can use the [ignoring comment tags](https://github.com/Taritsyn/WebMarkupMin/wiki/Ignoring-fragments-of-markup).

`</br>` is not an optional HTML end tag. This syntax is not acceptable from the point of view of HTML standard. You can check this with a [validator](https://validator.w3.org/): 

```
Error: End tag br.
From line 11, column 99; to line 11, column 103
r</a> <br></br>sit am
```

**Comment by kaushambi2612** [comment]
Ok, thanks for the prompt reply! 
I am receiving the HTML from a different source. I think it's better to get the wrong tag corrected.
