### ISSUE TITLE
Using this library to generate minified bundles and saving them to disk in netcore?

### ISSUE THREAD

**Issue by aloksharma1** [Taritsyn/WebMarkupMin#127]
Hello,

i have been using this library since mvc4 and for bundles i use ajax min to generate, bundle and save static files, that i am sure will not change much... since your library implement many different providers i was wondering if i can grab the result of your generation, bundle the css/js file in a single place namely bundle.min.css & bundle.min.js and save them to disk for future uses (until a file is changed).

this will save a lot of processing power and caching memory for those files which hardly changes in their lifetime after the application is deployed e.g. jquery & fixed plugins, awaiting your reply.

**Comment by Taritsyn** [comment]
Hello, Alok!

This library is not intended for this purpose.

I recommend that you look at the [BundlerMinifier](https://github.com/madskristensen/BundlerMinifier) and [Smidge](https://github.com/Shazwazza/Smidge) projects.

**Comment by aloksharma1** [comment]
Thank you, i dont see BundleMinifier is useful in my case, but Smidge looks promising.
