### ISSUE TITLE
Internal html character being escaped

### ISSUE THREAD

**Issue by davidlouth1** [Taritsyn/WebMarkupMin#131]
We have html that contains placeholders instead of actual values that are required by 3rd parties. It's in the format of <%some_var%>. This is common with many email providers that do things like providing unsubscribe links. The leading '<' character of the internal property is getting escaped.

Ex. `<a href="<%3rd_party_var%>" ....` is getting minified to `<a href="&lt;%3rd_party_var%> ...`

I'm using these settings:

`var htmlMinifier = new HtmlMinifier(new HtmlMinificationSettings(){ 
  AttributeQuotesRemovalMode=HtmlAttributeQuotesRemovalMode.KeepQuotes,
  UseShortDoctype=false,
  RemoveOptionalEndTags = false}
);`

I didn't see a setting that would address this. Ideally, this is just left alone without needing to use the ignore workaround.

Thanks,
Dave

**Comment by Taritsyn** [comment]
Hello, David!

Unfortunately, if I implement the ability to disable HTML encoding of attribute values, then a lot of things can break. The correct implementation of this functionality will require a serious rewrite of the parser.

In general, I leave this task until the next major release.

**Comment by Taritsyn** [comment]
For now, I can only recommend that you disable minification for these code blocks by using [ignoring HTML comments](https://github.com/Taritsyn/WebMarkupMin/wiki/Ignoring-fragments-of-markup).

**Comment by davidlouth1** [comment]
Thanks, is there a reason why the end ‘>’ char is not encoded? Seems inconsistent.

Dave

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Taritsyn** [comment]
> Thanks, is there a reason why the end ‘>’ char is not encoded? Seems inconsistent.

This is minimum HTML encoding of attribute value for compliance with HTML standard.
