### ISSUE TITLE
Can't minify multiple documents in parallel?

### ISSUE THREAD

**Issue by edumbell** [Taritsyn/WebMarkupMin#133]
Hi, I am using an instance of WebMarkupMin.Core.HtmlMinifier 2.9 to minify a large number of emails but it is too slow.  I see CPUs are barely being used, so tried to run the minification in e.g. a Parallel.For, but nothing I do improves performance or uses more CPUs.  Do you have a static lock around the main work?  Do you need that?   I could understand if each instance has some contested resource, but it would be nice if we could construct an instance per thread and not have them interfere with each other.

I have also tried setting all "Minify..." and "Remove..." settings to false but it doesn't seem to improve performance at all.  Any other suggestions much appreciated!

**Comment by Taritsyn** [comment]
Hello!

> Do you have a static lock around the main work?

Locks are used only at the instance level.

> Any other suggestions much appreciated!

 1. Try running the minifier under .NET 5.
 2. Try implementing a pool of `HtmlMinifier` instances (you can use the [Microsoft.Extensions.ObjectPool](https://www.nuget.org/packages/Microsoft.Extensions.ObjectPool/)  library as a basis).
