### ISSUE TITLE
.Net 6 Support?

### ISSUE THREAD

**Issue by xbaha** [Taritsyn/WebMarkupMin#134]
Can you update the NuGet package to support .Net 6?

**Comment by Taritsyn** [comment]
I'll do it in the next few days.

**Comment by Taritsyn** [comment]
As I understand it, you need the WebMarkupMin.AspNetCore6 package?

**Comment by xbaha** [comment]
Yes! Thank you so much!

**Comment by Taritsyn** [comment]
Hello!

This functionality was implemented in [version 2.11.0](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.11.0).  [Corresponding section of the documentation](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-Core-6) has also been added.

**Comment by xbaha** [comment]
Thanks a lot! Already installed WebMarkupMin.AspNetCore6 and looks great...
