### ISSUE TITLE
Blank page response

### ISSUE THREAD

**Issue by ghost** [Taritsyn/WebMarkupMin#138]
When I am using it for my .net core 6 MVC web application, the response page got just blank.  I tried to use ExactUrlMatcher("/") and then only the page worked. But it's without any changes.

Please help as I was a big fan of compressing HTML, CSS, and JS but post .net core, I did not find any working solution. I see the reference website you shared is what I am looking for. HTML without unwanted spaces in between tags. Compressed JS and CSS.

Kindly let me know how can I solve it.

//Add response caching service.
            services.AddResponseCaching();

            // Add WebMarkupMin services for minify HTML, CSS and JS -- Start
            services.AddWebMarkupMin(options =>
            {                
                options.AllowMinificationInDevelopmentEnvironment = true;
                options.AllowCompressionInDevelopmentEnvironment = true;
            })
            .AddHtmlMinification(options =>
            {
                options.SupportedHttpMethods = new HashSet<string> { "GET", "POST" };
                //options.ExcludedPages = new List<IUrlMatcher>
                //{
                //    new ExactUrlMatcher("/"),
                //    new ExactUrlMatcher("/Identity/Account/Login"),
                //    new ExactUrlMatcher("/PORRESTL07MODLV1M001V1BSAF001CNFG001PRFL/GetList"),
                //};
                HtmlMinificationSettings settings = options.MinificationSettings;
                settings.RemoveRedundantAttributes = true;
                settings.RemoveHttpProtocolFromAttributes = true;
                settings.RemoveHttpsProtocolFromAttributes = true;

                options.CssMinifierFactory = new NUglifyCssMinifierFactory();
                options.JsMinifierFactory = new NUglifyJsMinifierFactory();
            })
            .AddXhtmlMinification(options =>
            {
                options.SupportedHttpMethods = new HashSet<string> { "GET", "POST" };
                //options.ExcludedPages = new List<IUrlMatcher>
                //{
                //    new ExactUrlMatcher("/"),
                //    new ExactUrlMatcher("/Identity/Account/Login"),
                //    new ExactUrlMatcher("/PORRESTL07MODLV1M001V1BSAF001CNFG001PRFL/GetList"),
                //};
                XhtmlMinificationSettings settings = options.MinificationSettings;
                settings.RemoveRedundantAttributes = true;
                settings.RemoveHttpProtocolFromAttributes = true;
                settings.RemoveHttpsProtocolFromAttributes = true;

                options.CssMinifierFactory = new KristensenCssMinifierFactory();
                options.JsMinifierFactory = new CrockfordJsMinifierFactory();
            })
            .AddXmlMinification(options =>
            {
                XmlMinificationSettings settings = options.MinificationSettings;
                settings.CollapseTagsWithoutContent = true;
            })
            .AddHttpCompression(options =>
            {
                options.CompressorFactories = new List<ICompressorFactory>
                {
                    new BrotliCompressorFactory(new BrotliCompressionSettings
                    {
                        Level = 1
                    }),
                    new DeflateCompressorFactory(new DeflateCompressionSettings
                    {
                        Level = CompressionLevel.Fastest
                    }),
                    new GZipCompressorFactory(new GZipCompressionSettings
                    {
                        Level = CompressionLevel.Fastest
                    })
                };
            });

            // Override the default logger for WebMarkupMin.
            services.AddSingleton<IWmmLogger, WmmThrowExceptionLogger>();

**Comment by Taritsyn** [comment]
Hello!

Try disabling a brotli compression.

**Comment by ghost** [comment]
NO effect.
I commented package
WebMarkupMin.AspNet.Brotli" Version="2.10.0" 
then commented 
 //new BrotliCompressorFactory(new BrotliCompressionSettings
                    //{
                    //    Level = 1
                    //}),

still no change.

**Comment by Taritsyn** [comment]
Try to reproduce this error in the form of demo project and send me a link to it.

**Comment by Sausbolle** [comment]
I think I have similar problem where WebMarkupMin at random times gives empty page response (0 bytes).

This occurs if I have `AllowCompressionInDevelopmentEnvironment` set to `true`. So to avoid this bug `AllowCompressionInDevelopmentEnvironment` needs to be set to `false`.

It is hard to reproduce since when it occurs it is either every second pageload is empty or it gets into an mode of many empty loads then many good loads. And thus I have not been able to pinpoint to the actual cause and produce a bugtest code. 

I've tried to narrow down the code that causes without luck. When I think I have it narrowed down (consistently trigger bug) and try to make bugtest code by removing unrelated pure HTML it suddenly don't occur any more for no apparent reason.
But I suspect bug is related to `async ViewComponent` or `Html.PartialAsync` calls, but this is pure speculation.

One additional thing I noticed in logs is that when page loads correctly the `Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserRefreshMiddleware` failed to load and these two Debug messages are logged (neither is present in log when 0 byes page is served).
```
DBG - Response markup is scheduled to include browser refresh script injection.
DBG - Unable to configure browser refresh script injection on the response.
```
I hope some of this info will help you narrow down what the cause might be.

_I have not tested in production environment to see if bug is present there too with the code I have yet_

**Comment by Sausbolle** [comment]
Created a minimal code that causes the error
Running ASP .Net 6 (6.0.402)

```
using Microsoft.AspNetCore.Builder;
using WebMarkupMin.AspNetCore6;
using WebMarkupMin.AspNet.Common.UrlMatchers;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddWebMarkupMin(options =>
{
    options.AllowCompressionInDevelopmentEnvironment = true;
})
    .AddHttpCompression(
        // There is always an option to exclude the routes that returns string and not IActionResult  to make it work
        //options.ExcludedPages = new List<IUrlMatcher> {new ExactUrlMatcher("/") };
    });

var app = builder.Build();

app.UseWebMarkupMin();

// Will become blank if AllowCompressionInDevelopmentEnvironment is true or Production enviroment.
// ...and cause an "Headers are read-only, response has already started." Exception
app.MapGet("/", () => "Will become blank and cause error.");

app.Run();
```

**Comment by Taritsyn** [comment]
Hello!

I tried to fix all the above errors in [version 2.13.0](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.13.0).

**Comment by Sausbolle** [comment]
Looks like the update fixed the problem. Tested on more complex code that experienced it (and the minimal code) and looks like it works like a charm now.
Thanks for looking into this and the update :)

**Comment by Taritsyn** [comment]
In this case, it was possible to fix only reproducible errors that lead to the display of a blank page. But, unfortunately, there are also [non-reproducible errors](https://github.com/Taritsyn/WebMarkupMin/issues/147).
