### ISSUE TITLE
License, compatibility with BSD

### ISSUE THREAD

**Issue by lofcz** [Taritsyn/WebMarkupMin#139]
We'd like to use WebMarkupMin in a 3-Clause BSD licensed project. This would require us to license our entire project under Apache 2.0, that effectively prevents us from using WMM.

- are there any dependencies in WMM that would prevent dual licensing WMM under Apache 2.0/3-Clause BSD?
- is there a will to dual license WMM under Apache 2.0/3-Clause BSD?

Legal bindings between Apache 2.0 and 3-Clause BSD don't differ much, if dual licensing would be possible it would unblock our use case and possibly other projects in a similar situation.

**Comment by Taritsyn** [comment]
Hello, Matěj!

I don't plan to change the current license.

**Comment by lofcz** [comment]
Thanks for a quick reply, would you be open to grant a specific FOSS project a 3-Clause BSD license for WMM?

**Comment by Taritsyn** [comment]
I do not know how to do this.
