### ISSUE TITLE
HttpCompression Algorithm Priority

### ISSUE THREAD

**Issue by josh-sachs** [Taritsyn/WebMarkupMin#14]
Is there a way to set the compression algorithm priority?   Right now it appears to default to deflate when accepted by the client, and I don't see a way to change that to gzip.

**Comment by Taritsyn** [comment]
Hello,  Kudoz83!

In [WebMarkupMin 2.2.0](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.2.0) fixed this problem.

To change a priority of compression algorithm swap the compressor factories:

``` csharp
…
.AddHttpCompression(options =>
{
    options.CompressorFactories = new List<ICompressorFactory>
    {
        new GZipCompressorFactory(),
        new DeflateCompressorFactory()
    };
})
;
```
