### ISSUE TITLE
problem dont use Quotes in Html Attribute

### ISSUE THREAD

**Issue by vzsoft** [Taritsyn/WebMarkupMin#144]
hi

i need use 1 quot (') in Html Attributes 

`
<button data-role='button test'>Test</button>
`

but  Minify output 2 Quotes=>

`
<button data-role="button test">Test</button>
`

How do I solve this problem?

thank you

**Comment by Taritsyn** [comment]
Hello!

While this problem cannot be solved, but in future releases I can add the appropriate feature.

**Comment by Taritsyn** [comment]
Hello!

This feature is implemented in [version 2.14.0](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.14.0).
