### ISSUE TITLE
Check for Content-Length in response headers

### ISSUE THREAD

**Issue by billbogaiv** [Taritsyn/WebMarkupMin#15]
Note: This may or may not be specific to ASP.NET Core.

Currently, if middleware upstream sets the `Content-Length` header (i.e. [StaticFiles](https://github.com/aspnet/StaticFiles/blob/bbf1478821c11ecdcad776dad085d6ee09d8f8ee/src/Microsoft.AspNetCore.StaticFiles/StaticFileContext.cs#L310)), then usage of `WebMarkupMin` results in a `200`, but no content. This is because the resulting content-size is no longer the same as reported by the header-value. My current resolution is to insert my own middleware to remove the header:

``` csharp
app.UseWebMarkupMin();

app.Use(async (context, next) =>
{
    await next();

    if (context.Response.Headers.ContainsKey("Content-Length"))
    {
        context.Response.Headers.Remove("Content-Length");
    }
});

app.UseStaticFiles();
```

A bit more info. is posted [here](https://www.billboga.com/posts/compression-and-static-files-in-aspnet-core-10-using-kestrel).

**Comment by Taritsyn** [comment]
Hello, Bill!

In [WebMarkupMin 2.2.0](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.2.0) fixed this error.

Thanks for information! Instead of removing the `Content-Length` HTTP header, I change its value.
