### ISSUE TITLE
The minifier does not compress the content if there is code in the html

### ISSUE THREAD

**Issue by gurkantuna** [Taritsyn/WebMarkupMin#156]
Minifier actually works just fine but I realized much later that if I use some code rows with `<pre><code>` tags in html content it doesn't minify the code.

This page is containing some code rows and it doesn't minify

https://gurkantuna.com/article/3/flow-chart-visual-programming

![image](https://user-images.githubusercontent.com/55924924/230851338-9617fa07-ed59-447a-b748-f1eb53bedf6f.png)

<hr>

A non-software article that I've never used code for and minifed well

https://gurkantuna.com/article/1/soluk-mavi-nokta

![image](https://user-images.githubusercontent.com/55924924/230851746-f1cccf08-edb7-4ca9-8351-31e26619f874.png)

I've reviewed but I cannot find any parameter for this usage. Are there any parameters for this usage? If not, I think this case should be addressed.

**Comment by Taritsyn** [comment]
Hello, Gürkan!

> This page is containing some code rows and it doesn't minify
>
> https://gurkantuna.com/article/3/flow-chart-visual-programming

This page contains a syntax error:

Line 323, Column 25: **HTML_PARSING_ERROR.** During parsing of HTML-code error has occurred.

```
Line 322:         |   `--  STOP;/    
Line 323:         |-- A5.  IF num < 0 PRINT "Don't know" GOTO A1;/
----------------------------------^
Line 324:         |-- A6.  sum=1;/

```

The `<` symbol needs to be HTML encoded (`&lt;`).

To detect such errors I recommend you to write [your own logger](https://github.com/Taritsyn/WebMarkupMin/wiki/Loggers) or use the built-in logger (`ThrowExceptionLogger` class). If you use ASP.NET Core, then the logger for WebMarkupMin needs to be registered in the `Program.cs` file as follows:

```csharp
…
using IWmmLogger = WebMarkupMin.Core.Loggers.ILogger;
using WmmThrowExceptionLogger = WebMarkupMin.Core.Loggers.ThrowExceptionLogger;
…

var builder = WebApplication.CreateBuilder(args);
…

// Override the default logger for WebMarkupMin.
builder.Services.AddSingleton<IWmmLogger, WmmThrowExceptionLogger>();
…
```

**Comment by gurkantuna** [comment]
Hello @Taritsyn,

This is great! You really thought of everything beforehand, what I needed was a logger. Because many pages with code have the same case. I will review my html content again after the logger implementation. Thanks for your help.
