### ISSUE TITLE
drop minification in case of errors

### ISSUE THREAD

**Issue by TheSquiffy** [Taritsyn/WebMarkupMin#16]
If html output to be processed has errors the whole request fails.
There is no way to not minify in case of errors.

**Comment by Taritsyn** [comment]
Replace a `ThrowExceptionLogger` to `NullLogger` or your custom logger (see [“Loggers”](https://github.com/Taritsyn/WebMarkupMin/wiki/Loggers) section of the documentation).

In [ASP.NET 4.X Extensions](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-4.X-Extensions) this is done in the following way:

``` csharp
DefaultLogger.Current = new MyLogger();
```

In [ASP.NET Core 1.X Middleware](https://github.com/Taritsyn/WebMarkupMin/wiki/WebMarkupMin:-ASP.NET-Core-1.X) is done as follows:

``` csharp
services.AddSingleton<WebMarkupMin.Core.Loggers.ILogger, MyLogger>();
```
