### ISSUE TITLE
DotNet 8 support

### ISSUE THREAD

**Issue by parmarnishant** [Taritsyn/WebMarkupMin#161]
Hi,

Is this supported in .net 8 preview 5 ?

**Comment by Taritsyn** [comment]
Hello!

In .NET 8 try using the [WebMarkupMin.AspNetCore7](https://www.nuget.org/packages/WebMarkupMin.AspNetCore7/) module for now.

**Comment by Taritsyn** [comment]
Hello!

This feature is implemented in [version 2.15.0](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.15.0).

**Comment by Taritsyn** [comment]
Hello!

Now you can use a [WebMarkupMin.AspNetCore8](https://www.nuget.org/packages/WebMarkupMin.AspNetCore8) module.
