### ISSUE TITLE
<button> type attribute with "submit" value is removed

### ISSUE THREAD

**Issue by dang-le** [Taritsyn/WebMarkupMin#162]
From changelog v2.7.0 - September 24, 2019, the <button> type attribute with "submit" is considered redundant and automatically removed. This will cause an issue because it's rendered differently for Microsoft Edge.

We should always specify the type attribute for the button. The default type for Microsoft Edge is "button", while in other browsers (and in the W3C specification) it is "submit". Thank you.

Site Reference: https://www.w3schools.com/jsref/prop_pushbutton_type.asp#:~:text=The%20default%20type%20for%20Internet,)%20it%20is%20%22submit%22.

Changelog v2.7.0 - September 24, 2019: https://github.com/Taritsyn/WebMarkupMin/blob/master/CHANGELOG.md#v270---september-24-2019

**Comment by Taritsyn** [comment]
Hello, Dang!

> The default type for Microsoft Edge is "button", while in other browsers (and in the W3C specification) it is "submit". 

Just now I checked this behavior for Internet Explorer 11 and Microsoft Edge 114.0.1823.67, the default value is `submit`. 

You can prevent the removing of this attribute by using the following settings:

```csharp
new HtmlMinificationSettings()
{
    …
    PreservableAttributeList= "button[type]",
    …
}
```
