### ISSUE TITLE
Previously worked

### ISSUE THREAD

**Issue by christopherdude** [Taritsyn/WebMarkupMin#163]
I had everything working for several years, however suddenly it all just stopped minifying for some reason.  This particular project was using Web Forms.  Were there any breaking changes I'm not finding?

**Comment by christopherdude** [comment]
I should also note - this works in DEV, but not in PROD.  And yes, I have everything set to configure for usage, no matter the environment.  There weren't any new "server" requirements, were there?

**Comment by Taritsyn** [comment]
Hello, Christopher!

Are you using the following settings?

```csharp
    …
    public class WebMarkupMinConfig
    {
        public static void Configure(WebMarkupMinConfiguration configuration)
        {
            configuration.AllowMinificationInDebugMode = true;
            configuration.AllowCompressionInDebugMode = true;
            …
```

It is also possible that errors occur when parsing HTML content. I recommend you to write [your own logger](https://github.com/Taritsyn/WebMarkupMin/wiki/Loggers) or use the built-in logger (`ThrowExceptionLogger` class). If you use ASP.NET Web Forms, then the logger for WebMarkupMin needs to be registered in the `App_Start/WebMarkupMinConfig.cs` file as follows:

```csharp
using WebMarkupMin.Core.Loggers;
…
DefaultLogger.Current = new ThrowExceptionLogger();
```

**Comment by Taritsyn** [comment]
Hello, Christopher!

Did my advice help you?

**Comment by christopherdude** [comment]
Thank you for your patience!  In using your method of throwing an exception, this is what came through:

{"Category: JS_MINIFICATION_ERROR\r\nMessage: Expected '(': {\r\nFile: /\r\nLine number: 772\r\nColumn number: 19\r\nSource fragment:\r\n\r\nLine 771:             }\r\nLine 772:             catch {\r\n-----------------------------^\r\nLine 773:                 //debugger;\r\n\r\n"}

**Comment by christopherdude** [comment]
By commenting out the following line, everything seems to work..

DefaultJsMinifierFactory.Current = new MsAjaxJsMinifierFactory();

**Comment by Taritsyn** [comment]
Hello, Christopher!

```
Category: JS_MINIFICATION_ERROR
Message: Expected '(': {
File: /
Line number: 772
Column number: 19
Source fragment:

Line 771:             }
Line 772:             catch {
-----------------------------^
Line 773:                 //debugger;
```

It seems that JS minifier perceives the `catch` block without a exception value as syntax error.

It expects instead of this line:

```js
    catch {
```
Expects the following line:

```js
    catch (e) {
```

If you are using the WebMarkupMin.MsAjax or WebMarkupMin.Yui module, then replace it with a more modern module -  [WebMarkupMin.NUglify](https://www.nuget.org/packages/WebMarkupMin.NUglify/):

**Comment by christopherdude** [comment]
Will do - thanks for the fast reply.  I'm actually using the latest 2.14.0 from NuGet.  Does that not have that latest module?

**Comment by Taritsyn** [comment]
After installing the WebMarkupMin.NUglify module, this line:

```csharp
DefaultJsMinifierFactory.Current = new MsAjaxJsMinifierFactory();
```

Need to be replaced with the following line:

```csharp
DefaultJsMinifierFactory.Current = new NUglifyJsMinifierFactory();
```

**Comment by Taritsyn** [comment]
> I'm actually using the latest 2.14.0 from NuGet. Does that not have that latest module?

[Microsoft Ajax Minifier](https://github.com/microsoft/ajaxmin) and [YUI Compressor for .NET](https://github.com/YUICompressor-NET/YUICompressor.NET) libraries have been deprecated.

It looks like you are using a WebMarkupMin.MsAjax module. Uninstall the WebMarkupMin.MsAjax package and then install the WebMarkupMin.NUglify package. Replace the corresponding namespaces and update the code as in the previous post.

**Comment by christopherdude** [comment]
That did it!  Thank you so much.  By the way, do you have a minification setting in here for *.svg?

**Comment by Taritsyn** [comment]
The WebMarkupMin does not have an SVG minifier.

If SVG code is embedded in HTML code, then it is minified according to rules similar to XML minification. 

For individual `.svg` files, you can use an XML minifier (embedded scripts and styles will not be modified). But `.svg` files are static files and the WebMarkupMin.AspNet4.WebForms module will not work for them. For static files, you will need a [WebMarkupMin.AspNet4.HttpModules](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-4.X-HTTP-modules) module with `XmlMinificationModule` and may require special IIS configuration.
