### ISSUE TITLE
XML minification

### ISSUE THREAD

**Issue by LuckyTil** [Taritsyn/WebMarkupMin#164]
`
.AddXmlMinification(
    options => { options.MinificationSettings.CollapseTagsWithoutContent = true; } )
`

When process to download XML with encoding "windows-1251", tags (maybe attributes too) with Cyrillic content become corrupt.

Example

Corrupted value:
`
<POINTNM>пїЅпїЅпїЅпїЅпїЅ пїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅ пїЅпїЅпїЅ2</POINTNM>
`

Correct value:
`
<POINTNM>Пункт тестування ДЗЮ2</POINTNM>
`

**Comment by Taritsyn** [comment]
Hello, Ihor!

 1. Which WebMarkupMin ASP.NET extension are you using?
 2. Is this XML code generated programmatically or is it a static file?

**Comment by LuckyTil** [comment]
>1. Which WebMarkupMin ASP.NET extension are you using?

WebMarkupMin.AspNetCore5 2.14.1

>2. Is this XML code generated programmatically or is it a static file?

XML generated programmatically and returned due ControllerBase.File method, stream overload, content type "text/xml"

**Comment by Taritsyn** [comment]
> XML generated programmatically and returned due ControllerBase.File method, stream overload, content type "text/xml"

This extension determines the text encoding based on the `ContentType` property of response. Try replacing the `text/xml` content type by the `text/xml; charset=windows-1251`.

**Comment by LuckyTil** [comment]
> This extension determines the text encoding based on the ContentType property of response. Try replacing the text/xml content type by the text/xml; charset=windows-1251.

Why did XML header not used to determine encoding?
```xml
<?xml version="1.0" encoding="windows-1251"?>
```

**Comment by Taritsyn** [comment]
> Why did XML header not used to determine encoding?

Because text content is read from the response and at the time of reading, [data is available only as an array of bytes](https://github.com/Taritsyn/WebMarkupMin/blob/bf0a98bbb6f52287b1143af0b33574668f2a7322/src/WebMarkupMin.AspNetCore1/BodyWrapperStreamBase.cs#L347-L354). To convert an array of bytes to text, we need to know the encoding.

**Comment by LuckyTil** [comment]
Thank You, @Taritsyn
