### ISSUE TITLE
Question regarding asp.net webforms  > .ascx

### ISSUE THREAD

**Issue by VincentVanHulstPersonal** [Taritsyn/WebMarkupMin#165]
Hello, i was wondering if it would be possible to also minify the content of the html output rendered through .ascx controls? I have some .aspx pages with placeholders that load .ascx files on page init. The output of the .aspx page is minified/compressed but not the contents of the .ascx files.

**Comment by Taritsyn** [comment]
Hello, Vincent!

Quite non-standard functionality, similar to a CMS. I definitely haven't tested such things.

There are two ways to solve this problem:
 1. Use the [WebMarkupMin.AspNet4.HttpModules](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-4.X-HTTP-modules) module instead of the WebMarkupMin.AspNet4.WebForms module.
 1. Try to reproduce this error in the form of demo project and send me a link to it. Then I'll see how I can fix this problem.

**Comment by Taritsyn** [comment]
HTML output of the following code is completely minified:

```csharp
protected void Page_Init(object sender, EventArgs e)
{
    var myControl = this.LoadControl("~/Controls/MyControl.ascx") as MyControl;
    myPlaceholder.Controls.Add(myControl);
}
```

**Comment by VincentVanHulstPersonal** [comment]
Thank you for this feedback. I will dive into this again. Only other thing that i can think of is that we have some nested .ascx loading. (index.aspx > main.ascx > overview.ascx).

**Comment by VincentVanHulstPersonal** [comment]
Furthermore I have index.aspx  > Inherits WebMarkupMin.AspNet4.WebForms.MinifiedAndCompressedHtmlPage
The .ascx's just inherit > System.Web.UI.UserControl  Is that correct?

**Comment by Taritsyn** [comment]
Yes, this is correct.

**Comment by Taritsyn** [comment]
Does the `.ascx` file contain the `pre` and `textarea` tags, or [ignoring comment tags](https://github.com/Taritsyn/WebMarkupMin/wiki/Ignoring-fragments-of-markup)?

**Comment by VincentVanHulstPersonal** [comment]
Ok i think for now we can close this issue; i now see some html parsing errors in de logger. Probably that is the issue. Regarding your question: we do have textarea tags.

**Comment by VincentVanHulstPersonal** [comment]
Yes problem solved; i found invalid markup in some CMS-content. Thank you for your help.

**Comment by Taritsyn** [comment]
Content of tags listed above is never minified.

I recommend you to write [your own logger](https://github.com/Taritsyn/WebMarkupMin/wiki/Loggers) or use the built-in logger (`ThrowExceptionLogger` class). If you use ASP.NET Web Forms, then the logger for WebMarkupMin needs to be registered in the `App_Start/WebMarkupMinConfig.cs` file as follows:

```csharp
using WebMarkupMin.Core.Loggers;
…
DefaultLogger.Current = new ThrowExceptionLogger();
```
