### ISSUE TITLE
Unclosed td / th tags on PartialView

### ISSUE THREAD

**Issue by danFbach** [Taritsyn/WebMarkupMin#166]
In an existing `<table>` that i intend to inject rows (`<tr>`) into. I call an action with javascript, the action returns a PartialView, what is returned looked something like:

```html
<tr>
    <td>cell 1
    <td>cell 2
</tr>
<tr>
    <td>cell 1
    <td>cell 2
</tr>
```
with no closing tags.

When unclosed `<td>` or `<th>` tags as a inside complete `<table>` element, browsers seem to have no problem parsing it into a valid table, but when the unclosed tags a returned and injected with javascript, no parsing occurs and broken html is the result.

**Comment by Taritsyn** [comment]
Hello, Dan!

Optional tags are defined by HTML specification. There is a [good article](https://meiert.com/en/blog/optional-html/) on this theme.

You can disable this behavior by using the `RemoveOptionalEndTags` and `PreservableOptionalTagList` options (see the [documentation](https://github.com/Taritsyn/WebMarkupMin/wiki/HTML-Minifier) for details).

**Comment by danFbach** [comment]
Hey @Taritsyn,
I apologize for reporting this. After testing with `<!--wmm:ignore-->` around my view code, i found that the unminified html produced the same result, which helped me localize my problem to my method of injection in javascript.
Thanks for responding, anyway!
