### ISSUE TITLE
Invalid HTML Minification Result

### ISSUE THREAD

**Issue by ZarehD** [Taritsyn/WebMarkupMin#167]
Minified content is clipped before the closing body+html tags.

I'm not certain when this started happening, but I _think_ it was after upgrading to 2.13.9 or 2.14.0. The code is currently using _WebMarkupMin.Core_ v2.14.0 (which appears to be the latest). Just for thoroughness, I tried using the v2.15.2 versions of WebMarkupMin.AspNetCore (6, 7, and 8), but unfortunately the problem persisted.

The input HTML content is stored in a string that is then passed to the Minify() method.

```C#
var pageContent = await httpClient.GetStringAsync(
	requestUri, ct).ConfigureAwait(false);

var htmlMinifierSettings = services.GetService<HtmlMinificationSettings>(); // none registered, returns null
var cssMinifier = host.Services.GetService<ICssMinifier>(); // none registered, returns null
var jsMinifier = host.Services.GetService<IJsMinifier>(); // none registered, returns null
var optimizer = new HtmlMinifier(htmlMinifierSettings, cssMinifier, jsMinifier);

var result = optimizer.Minify(pageContent, Encoding.UTF8);
if (!result.Errors.Any())
{
	// pageContent is valid HTML before the assignment...
	pageContent = result.MinifiedContent;
	// pageContent is invalid HTML after the assignment...
}
```

I've attached a zip file containing two markdown files with the before and after HTML. [WMM_Minification_Error.zip](https://github.com/Taritsyn/WebMarkupMin/files/13607713/WMM_Minification_Error.zip)

If you would like to take a look at the actual code where this is happening, you can find it in my [AspNetStatic](https://github.com/ZarehD/AspNetStatic) repo. You'll find the relevant code in the _StaticPageGenerator.cs_ file in the main project. You can run the sample project to generate the minified HTML files (i.e. index.html, etc. in wwwroot folder).

**Comment by Taritsyn** [comment]
Hello, Zareh!

> Minified content is clipped before the closing body+html tags.

Optional tags are defined by HTML specification. There is a [good article](https://meiert.com/en/blog/optional-html/) on this theme.

You can disable this behavior by using the `RemoveOptionalEndTags` and `PreservableOptionalTagList` options (see the [documentation](https://github.com/Taritsyn/WebMarkupMin/wiki/HTML-Minifier) for details).

**Comment by ZarehD** [comment]
Hello Andrey, and thank you for the quick reply.

I'm glad the issue is with my lack of understanding rather than with the library ;-)

Thanks again for your help. Cheers!
