### ISSUE TITLE
.NET 6 -> .NET 8 (Markup minification not working)

### ISSUE THREAD

**Issue by hedronn** [Taritsyn/WebMarkupMin#168]
Having previously had the minification working in a .NET 6 project, I recently upgraded the project to .NET 8 and the WebMarkupMin.AspNetCore8 nuget package 2.15.2 and the minification has stopped working.

I have used the following code in the program.cs

builder.Services.AddWebMarkupMin(options =>
{
    options.AllowMinificationInDevelopmentEnvironment = true;
    options.AllowCompressionInDevelopmentEnvironment = true;
})
    .AddHtmlMinification(options =>
    {
        HtmlMinificationSettings settings = options.MinificationSettings;

        settings.RemoveRedundantAttributes = true;
        settings.RemoveHttpProtocolFromAttributes = true;
        settings.RemoveHttpsProtocolFromAttributes = true;
        settings.WhitespaceMinificationMode = WhitespaceMinificationMode.Medium;

        options.CssMinifierFactory = new NUglifyCssMinifierFactory();
        options.JsMinifierFactory = new NUglifyJsMinifierFactory();
    })
    .AddHttpCompression(options =>
    {
        options.CompressorFactories = new List<ICompressorFactory>
        {
            new BuiltInBrotliCompressorFactory(new BuiltInBrotliCompressionSettings
            {
                Level = CompressionLevel.Fastest
            }),
            new DeflateCompressorFactory(new DeflateCompressionSettings
            {
                Level = CompressionLevel.Fastest
            }),
            new GZipCompressorFactory(new GZipCompressionSettings
            {
                Level = CompressionLevel.Fastest
            })
        };
    });

Follows with...

app.UseWebMarkupMin();

Is there anyway I can check logs to determine the issue?

**Comment by Taritsyn** [comment]
Hello!

I recommend you to write [your own logger](https://github.com/Taritsyn/WebMarkupMin/wiki/Loggers) or use the built-in logger (`ThrowExceptionLogger` class). Logger for WebMarkupMin needs to be registered in the `Program.cs` file as follows:

```csharp
…
using IWmmLogger = WebMarkupMin.Core.Loggers.ILogger;
using WmmThrowExceptionLogger = WebMarkupMin.Core.Loggers.ThrowExceptionLogger;
…

var builder = WebApplication.CreateBuilder(args);
…

// Override the default logger for WebMarkupMin.
builder.Services.AddSingleton<IWmmLogger, WmmThrowExceptionLogger>();
…
```
