### ISSUE TITLE
< Symbol triggers HTML_MARKUP_ERROR

### ISSUE THREAD

**Issue by ghost** [Taritsyn/WebMarkupMin#17]
This HTML triggers HTML_MARKUP_ERROR.

Line 494: 
Line 495: …argin-top: 0; margin-bottom: 0"><font size="2">< 500mA</font></td></tr><tr><td nowrap style="…
----------------------------------------------------------^
Line 496: 

Is there a way to render the page without minifying when there is an exception?

**Comment by Taritsyn** [comment]
Hello, Emmanuel!

This issue has already been discussed - [“drop minification in case of errors”](https://github.com/Taritsyn/WebMarkupMin/issues/16).
