### ISSUE TITLE
minification is removing protocol from links

### ISSUE THREAD

**Issue by aloksharma1** [Taritsyn/WebMarkupMin#174]
hello, i need to preserve protocol for canonical url i dont care about other place as they are not so relevant for seo.

here is what i did:

 `PreservableAttributeList = "form[method=get i], input[type], [xmlns], button[type], link[rel=canonical i][href]",`
 
 but it seems this is not effective, its generating url as `<link rel="canonical" href="//www.mysite.com/contact-us">`
 
 what am i doing wrong?

**Comment by Taritsyn** [comment]
Hello, Alok!

Removing a protocol from the URLs can be disabled by using two properties: `RemoveHttpProtocol­FromAttributes` and `RemoveHttpsProtocol­FromAttributes` (see the [“HTML Minifier”](https://github.com/Taritsyn/WebMarkupMin/wiki/HTML-Minifier) section of documentation).

`PreservableAttributeList` property only prevents removing of attributes themselves.

**Comment by aloksharma1** [comment]
> Hello, Alok!
> 
> Removing a protocol from the URLs can be disabled by using two properties: `RemoveHttpProtocol­FromAttributes` and `RemoveHttpsProtocol­FromAttributes` (see the [“HTML Minifier”](https://github.com/Taritsyn/WebMarkupMin/wiki/HTML-Minifier) section of documentation).
> 
> `PreservableAttributeList` property only prevents removing of attributes themselves.

thanks, so basically it cant be turned off partially?

**Comment by Taritsyn** [comment]
> thanks, so basically it cant be turned off partially?

No.

**Comment by Taritsyn** [comment]
In general, you can only turn off it completely.
