### ISSUE TITLE
Why is SavedGzipInBytes a decimal?

### ISSUE THREAD

**Issue by rosemaryehlers** [Taritsyn/WebMarkupMin#18]
SavedGzipInBytes = OriginalGzipSize - MinifiedGzipSize;

But both OriginalGzipSize and MinifiedGzipSize are longs - having SavedGzipInBytes be a decimal seems unnecessary and confusing.

https://github.com/Taritsyn/WebMarkupMin/blob/master/src/WebMarkupMin.Core/MinificationStatistics.cs

**Comment by Taritsyn** [comment]
Hello, Rosemary!

Thanks for information.

**Comment by Taritsyn** [comment]
Hello, Rosemary!

In [WebMarkupMin 2.2.2](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.2.2) fixed this error.
