### ISSUE TITLE
close tag </head>, </body>, </html> not found

### ISSUE THREAD

**Issue by ghost** [Taritsyn/WebMarkupMin#19]
Hello,
I am using WebMarkupMin.AspNet4.Mvc V2.2.0 to minify my ASP.NET MVC C# project.
I changed my web.config as same as the following page.
http://stackoverflow.com/questions/28380236/how-to-configure-html-minification-in-asp-net-mvc
Then I added [MinifyHtml] to the HomeController class.
The WebMarkupMin.AspNet4.Mvc minifier worked fine but I noticed that the three close tags 
 `</head>, </body>, </html>` are not added to the minified output.
This symptom occurred for any simple cshtml pages.
If you can reproduce the problem, please fix it.

**Comment by Taritsyn** [comment]
Hello, Hiromi!

Removing of optional end tags is not an bug, but an feature. You can manage this feature by using the following configuration properties: `RemoveOptionalEndTags` and `PreservableOptionalTagList`.

**Comment by Taritsyn** [comment]
By the way, you need to [upgrade to version 2.X](https://github.com/Taritsyn/WebMarkupMin/wiki/How-to-upgrade-applications-to-version-2.X).

**Comment by ghost** [comment]
Thank you for your quick reply.
I am using WebMarkupMin.AspNet4.Mvc V2.2.0 .
Is this a version 2.X. you mentioned?
I tried all the four cases to set true/false to the RemoveOptionalEndTags and PreservableOptionalTagList .
But, the output result does not have these`</head>, </body>, </html>`end tags.
Am I doing something wrong?

**Comment by Taritsyn** [comment]
Are you trying to configure WebMarkupMin by using the `Web.config` file?

**Comment by ghost** [comment]
Yes.

**Comment by Taritsyn** [comment]
I recommend you to read [“How to upgrade applications to version 2.X”](https://github.com/Taritsyn/WebMarkupMin/wiki/How-to-upgrade-applications-to-version-2.X) section of the documentation.

**Comment by ghost** [comment]
My ASP.NET MVC project is created by VS2015 Update3.
I am using latest Nuget Package Manager and installed the WebMarkupMin.AspNet4.Mvc V2.2.0 .
I tried another method.
Previously I was using Web.config file to configure the settings for WebMarkupMin.AspNet4.Mvc .
Now, I removed WebMarkupMin settings in  Web.config file.
I added these filters to App_Start/FilterConfig.cs file.
   filters.Add(new CompressContentAttribute());
   filters.Add(new MinifyHtmlAttribute());
   filters.Add(new MinifyXmlAttribute());
The result was the same, the end tags did not found.
What I should do?

**Comment by Taritsyn** [comment]
It seems that you did not read carefully.

Looking for mentions of the `App_Start/WebMarkupMinConfig.cs` and `Global.asax` files in [“ASP.NET 4.X Extensions”](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-4.X-Extensions) section of the documentation.

**Comment by ghost** [comment]
Thank you for the information.
By using the App_Start/WebMarkupMinConfig.cs method you suggested, I could successfully minify the cshtml and I could find the end tags!
In this case, I did not set any configurations related to WebMarkupMin in Web.config file.

My remaining question is why my first trial was failed.
Do I have to use App_Start/WebMarkupMinConfig.cs method ? and Web.config file methed is not supported in WebMarkupMin.AspNet4.Mvc?

**Comment by Taritsyn** [comment]
> My remaining question is why my first trial was failed.
> Do I have to use App_Start/WebMarkupMinConfig.cs method ? and Web.config file methed is not supported in WebMarkupMin.AspNet4.Mvc?

Configuration via `Web.config` is not supported in version 2.X and [WebMarkupMin.AspNet4.Mvc](https://www.nuget.org/packages/WebMarkupMin.AspNet4.Mvc/) module. Most likely, you previously used version 1.X and [WebMarkupMin.Mvc](https://www.nuget.org/packages/WebMarkupMin.Mvc/) module.

By the way, it is written in [“How to upgrade applications to version 2.X”](https://github.com/Taritsyn/WebMarkupMin/wiki/How-to-upgrade-applications-to-version-2.X) section of the documentation.

**Comment by ghost** [comment]
Taritsyn, thank you for your reply.
All of my questions became cleared.
I think WebMarkupMin is a great tool.
I will try to use it not only for MVC but also for Core project.

**Comment by Vitaly9354** [comment]
Spent a bunch of time trying to figure out why this was happening :( This settings should be enabled by default.

**Comment by Taritsyn** [comment]
Hello, Vitaly!

> This settings should be enabled by default.

In this you are not right.

> Spent a bunch of time trying to figure out why this was happening :(

Maybe you should start getting acquainted with the library by reading the [documentation](https://github.com/Taritsyn/WebMarkupMin/wiki/HTML-Minifier)?
