### ISSUE TITLE
Adding WebMarkupMin with a ServiceStack .Net Core enabled project fails

### ISSUE THREAD

**Issue by RobSchoenaker** [Taritsyn/WebMarkupMin#20]
When adding WebMarkupMin to my project, I get a

**NotSupportedException: Stream does not support writing.**

```
System.NotSupportedException: Stream does not support writing.
   at System.IO.MemoryStream.SetLength(Int64 value)
   at WebMarkupMin.AspNetCore1.WebMarkupMinMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__6.MoveNext()
```

![image](https://cloud.githubusercontent.com/assets/4450207/20193417/2b90b200-a78e-11e6-9f02-6501fc698e7e.png)

The configure method:
```
    // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
    public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
    {
      loggerFactory.AddConsole(Configuration.GetSection("Logging"));
      loggerFactory.AddDebug();
      if (env.IsDevelopment())
      {
        app.UseDeveloperExceptionPage();
      }
      else
      {
        app.UseExceptionHandler("/Home/Error");
      }

      app.UseStaticFiles();

      app.UseWebMarkupMin();

      app.UseServiceStack(new AppHost());

      app.UseMvc(routes =>
      {
        routes.MapRoute(
                  name: "default",
                  template: "{controller=Home}/{action=Index}/{id?}");
      });
```

**Comment by Taritsyn** [comment]
Hello, Rob!

You could make a demonstration project, which reproduce this error.

**Comment by RobSchoenaker** [comment]
Will do. I will drop the link here

**Comment by Taritsyn** [comment]
OK

**Comment by RobSchoenaker** [comment]
Here you are:

[https://github.com/RobSchoenaker/WMWSS](url)

**Comment by mythz** [comment]
To save anyone spending any more time on this issue, this is now resolved in ServiceStack .Core NuGet packages from v1.0.28, more details at: https://forums.servicestack.net/t/net-core-razorformat-omission/3165/9?u=mythz

@Taritsyn BTW cool library, looking forward to using it future :)

**Comment by Taritsyn** [comment]
In [WebMarkupMin 2.2.2](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.2.2) fixed this error.

@RobSchoenaker Thanks for demonstration project.

@mythz I have tried to prevent such compatibility errors in the future.
