### ISSUE TITLE
Remove redundant attributes, except input

### ISSUE THREAD

**Issue by adrianiftode** [Taritsyn/WebMarkupMin#21]
We use some CSS selectors like `input[type=text]` and these won't work with `RemoveRedundantAttributes` since the `type=text` is the redundant one. I fixed this by changing the CSS, but do you plan to make these definitions configurable?

**Comment by Taritsyn** [comment]
Hello, Adrian!

I think, that worth to implement this feature.

It's only a matter of time. In the near future will be a lot of work, related with the transition to .NET Core 1.1.

**Comment by Taritsyn** [comment]
Hello, Adrian!

In [WebMarkupMin 2.2.3](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.2.3) solved this problem.

In configuration settings of HTML and XHTML minifiers was added one new property - `PreservableAttributeList` (default is empty). `PreservableAttributeList` property contains a comma-separated list of string representations of attribute expressions, that define what attributes can not be removed (e.g. `"form[method=get i], input[type], [xmlns]"`). Attribute expressions somewhat similar to the CSS Attribute Selectors. There are six varieties of the attribute expressions:

 * `[attributeName]`
 * `tagName[attributeName]`
 * `[attributeName=attributeValue]`
 * `tagName[attributeName=attributeValue]`
 * `[attributeName=attributeValue i]`
 * `tagName[attributeName=attributeValue i]`

**Comment by adrianiftode** [comment]
Many thanks!

**Comment by CumpsD** [comment]
Thanks, this is what I needed to get `type="text"` back on my `input`s :)

Curiosity question, what does the `i` mean in your examples?

**Comment by Taritsyn** [comment]
Hello, David!

`i` - ignore case.

**Comment by CumpsD** [comment]
Ah, thanks! :)

**Comment by Taritsyn** [comment]
Answers to some questions can be found in the [documentation](https://github.com/Taritsyn/WebMarkupMin/wiki).

**Comment by CumpsD** [comment]
Yeah, I read those :) Very good, thanks!
