### ISSUE TITLE
Exclude based on atrribute+value and/or tag name?

### ISSUE THREAD

**Issue by SimonCropp** [Taritsyn/WebMarkupMin#22]
Is there a way to exclude a node from minimization based on an attributes key + value and/or tag name?

**Comment by SimonCropp** [comment]
my current work around

```
var type = typeof(HtmlMinificationSettings).Assembly.GetType("WebMarkupMin.Core.GenericHtmlMinifier", true);
var fieldInfo = type.GetField("_tagsWithNotRemovableWhitespace", BindingFlags.Static | BindingFlags.NonPublic);
var hashSet = (HashSet<string>) fieldInfo.GetValue(null);
hashSet.Add("skipminify");
```

**Comment by Taritsyn** [comment]
Hello, Simon!

> Is there a way to exclude a node from minimization based on an attributes key + value and/or tag name?

There is no such feature.

> my current work around

What are tags you exclude this way?

**Comment by SimonCropp** [comment]
we use markdig https://github.com/lunet-io/markdig

which has support for http://knsv.github.io/mermaid/

the html is generates is 

```
<div class="mermaid">sequenceDiagram

Participant Subscriber1 As Subscriber1
Participant Subscriber2 As Subscriber2
Subscriber1 ->> Publisher: Subscribe to Message1
Publisher ->> Persistence: Store "Subscriber1 wants Message1"
Subscriber2 ->> Publisher: Subscribe to Message1
Publisher ->> Persistence: Store "Subscriber2 wants Message1"
</div>
```

which is then rendered on the client side

But if that is minified the newlines are lost and the DLS can no longer be interpreted.

**Comment by Taritsyn** [comment]
For your case need more universal solution. I plan to make the analogue of `<!-- htmlmin:ignore -->` from the [HTMLMinifier](https://github.com/kangax/html-minifier) project.

**Comment by SimonCropp** [comment]
that would work for me

**Comment by Taritsyn** [comment]
I think it will look like this:

``` html
<!--webmarkupmin:ignore-->
<div class="mermaid">sequenceDiagram

Participant Subscriber1 As Subscriber1
Participant Subscriber2 As Subscriber2
Subscriber1 ->> Publisher: Subscribe to Message1
Publisher ->> Persistence: Store "Subscriber1 wants Message1"
Subscriber2 ->> Publisher: Subscribe to Message1
Publisher ->> Persistence: Store "Subscriber2 wants Message1"
</div>
<!--/webmarkupmin:ignore-->
```

I will implement this task after [“Remove redundant attributes, except input”](https://github.com/Taritsyn/WebMarkupMin/issues/21) task. So far, will have to wait.

**Comment by SimonCropp** [comment]
thanks. i can live with my workaround till then

**Comment by Taritsyn** [comment]
Hello, Simon!

In [WebMarkupMin 2.2.4](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.2.4) solved this problem. Use the following code:

```html
<!--wmm:ignore-->
<div class="mermaid">sequenceDiagram

Participant Subscriber1 As Subscriber1
Participant Subscriber2 As Subscriber2
Subscriber1 ->> Publisher: Subscribe to Message1
Publisher ->> Persistence: Store "Subscriber1 wants Message1"
Subscriber2 ->> Publisher: Subscribe to Message1
Publisher ->> Persistence: Store "Subscriber2 wants Message1"
</div>
<!--/wmm:ignore-->
```

**Comment by SimonCropp** [comment]
Awesome. Thanks

**Comment by SimonCropp** [comment]
BTW just verified and works as advertised :)
