### ISSUE TITLE
Html comment in head tag is being minified despite settings

### ISSUE THREAD

**Issue by rosemaryehlers** [Taritsyn/WebMarkupMin#24]
Our website has an html comment inside the head tag that we'd like to preserve. I have tried setting RemoveHtmlComments and RemoveHtmlCommentsFromScriptsAndStyles to false, but this comment is still removed.

Minification settings:
```
var settings = new HtmlMinificationSettings(useEmptyMinificationSettings: true);
settings.SetProcessableScriptTypes(new List<string>() { "text/html" });
settings.PreserveCase = true;
settings.WhitespaceMinificationMode = WhitespaceMinificationMode.Safe;
settings.RemoveHtmlComments = false;
settings.RemoveHtmlCommentsFromScriptsAndStyles = false;
```

Unminified:
```
<head>
    <!-- MachineID: 171 -->
    <title>Home</title>
</head>
```

Minified:
`<head><title>Home</title></head>`

I can see html comments being preserved in the body, so it looks like those settings are merely not being applied when minifying the head tag. Is this expected behavior?

**Comment by Taritsyn** [comment]
Hello, Rosemary!

HTML comments are removed correctly. You can check this by using the [WebMarkupMin Online](http://webmarkupmin.apphb.com/minifiers/html-minifier).

It is possible, that you incorrectly configured the WebMarkupMin ASP.NET Extension. What ASP.NET extension you  are using?

**Comment by Taritsyn** [comment]
As I understand this problem has resolved itself?
