### ISSUE TITLE
NullReferenceException with FileContentResult in ASP.vNext RC1

### ISSUE THREAD

**Issue by justdmitry** [Taritsyn/WebMarkupMin#3]
I'm using `WebMarkupMin.AspNet5` `2.0.0-rc1` package in my ASP.vNext RC1 application.

When controller method returns `File` (not static file from `UseStaticFiles`, but file generated as result of controller action) - `WebMarkupMinMiddleware` fails with `NullReferenceException`.

Here is sample method body:

```
[Route("file.xml")]
public IActionResult GetFile()
{
    var xml = @"<xml version='1.0'><root><greeting>Hello, World</greeting></root>";
    var xmlBytes = System.Text.Encoding.UTF8.GetBytes(xml);
    return File(xmlBytes, "application/atom+xml", "feed.xml");
}
```

I created separate project with minimal code that demonstrates this error: [WebMarkupMin.AspNet5.FileActionResultError](https://github.com/justdmitry/WebMarkupMin.AspNet5.FileActionResultError)

**Comment by Taritsyn** [comment]
Hello, Dmitry!

In [WebMarkupMin 2.0.0 RC 4](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.0.0-rc.4) fixed this error.
