### ISSUE TITLE
Perfomance is very slow when a HTML comment is inside a JavaScript block

### ISSUE THREAD

**Issue by adrianiftode** [Taritsyn/WebMarkupMin#31]
I've mistakenly placed a HTML comment inside a JavaScript block that caused the time to load a page to increase from 200-300 ms to 6-7 seconds. Besides this, that block contained a quiet large JSON array, but removing that `comment` did the perf fix.

Obviously the comment shouldn't have been there, but I still think it is an issue if this causes such a drop in the load time.

**Comment by Taritsyn** [comment]
Hello, Adrian!

Thanks for information! I will look for the cause of this error.

**Comment by adrianiftode** [comment]
Great catch, Andrey! I also learned something really useful about Regexes.

Btw, I think the .build folder should be added to the .gitignore.

I saw you used the statistics info in your tests. Is there anything else to do besides writing an ILogger implementation to log the statistics? Are these statistics enabled by default?

Thanks!

**Comment by Taritsyn** [comment]
> Are these statistics enabled by default?

By default, generation of statistics is disabled, because it slightly reduces performance.

> Is there anything else to do besides writing an ILogger implementation to log the statistics?

Unfortunately, now in ASP.NET extensions is missing the ability to enable generation of statistics (logger always gets its equal to null), but in next release I will add this feature.

**Comment by Taritsyn** [comment]
Hello, Adrian!

> Unfortunately, now in ASP.NET extensions is missing the ability to enable generation of statistics (logger always gets its equal to null), but in next release I will add this feature.

I have added this feature in [version 2.3.0](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.3.0). In markup minification managers and options was added a new property - `GenerateStatistics` (default `false`).

**Comment by adrianiftode** [comment]
Many thanks!

2017-03-08 18:05 GMT+02:00 Andrey Taritsyn <notifications@github.com>:
