### ISSUE TITLE
Javascript with a less than sign

### ISSUE THREAD

**Issue by wizaerd** [Taritsyn/WebMarkupMin#32]
I'm surprised nobody has encountered this before, but I have with not only this minifier, but also the built in Microsoft.Ajax.Utilities version.

With the inline javascript minifier, if my javascript has a less than sign in it, which is pretty important in javascript, I get parse errors when the minifier hits.  If I remove the less than sign from my inline script, or place it outside the call to the CrockfordJsMinifier, then everything is ok.

What I did was create an Html helper to call inside of my razor page, which calls the minifier.  Nobody else has ran into this issue?

**Comment by Taritsyn** [comment]
Hello, Wizaerd!

Give an example of code and full error message.

**Comment by wizaerd** [comment]
I've tried narrowing it down.  I've attached 2 files, the first is an image of the error.  The second one is my cshtml file, renamed with a .txt extension so I could upload it, As far as the Minifier Html Helper, here is the code:

`public static MvcHtmlString JSMinify(this HtmlHelper helper, Func<object, object> markup)
        {
            string notMinifiedJs = (markup.DynamicInvoke(helper.ViewContext) ?? "").ToString();

            if (!Convert.ToBoolean(ConfigurationManager.AppSettings["MinifyJS"] ?? "false"))
            {
                return new MvcHtmlString(notMinifiedJs);
            }

            var jsMinifier = new CrockfordJsMinifier();
            var minifiedJS = jsMinifier.Minify(notMinifiedJs, true);
            return new MvcHtmlString(minifiedJS.MinifiedContent);
        }`

It's really odd because if I remove the ToggleMenus javascript call (in the cshtml file) it will work... If I remove the offending line of `if(formFieldCount <= 0)` it will also work.

[Index.cshtml.txt](https://github.com/Taritsyn/WebMarkupMin/files/828717/Index.cshtml.txt)
![error](https://cloud.githubusercontent.com/assets/2036918/23719420/88dd0c9e-03f8-11e7-8cf4-71e846432baa.png)

**Comment by Taritsyn** [comment]
What does this have to the WebMarkupMin? This is not a WebMarkupMin's exception.

**Comment by wizaerd** [comment]
The error only occurs when I use the WebMarkupMin.  Without the JSMinify code (which is the WebMarkupMin wrapper) I don't get the error and my page loads and functions fine.  The common denominator then is that using the WebMarkupMin classes causes this error.

**Comment by Taritsyn** [comment]
Hello, Wizaerd!

Your error occurs in the following line of `JSMinify` HTML-helper:

```csharp
string notMinifiedJs = (markup.DynamicInvoke(helper.ViewContext) ?? "").ToString();
```

You can check this by using the modified HTML-helper:

```csharp
public static MvcHtmlString JSMinify(this HtmlHelper helper, Func<object, object> markup)
{
	string notMinifiedJs = (markup.DynamicInvoke(helper.ViewContext) ?? "").ToString();

	return new MvcHtmlString("");
}
```

Your error is located in Razor-template. Solution for your problem described in the error message:

```
 If you intended to display a "<" character, use the "&lt;" HTML entity.
```

You just need to escape the `<` character:

```cshtml
<script type="text/javascript">
    @Html.JSMinify(@<text>
    var formFieldCount = 0;

    // listen for when an item is dropped onto the form
    document.addEventListener("fieldAdded", function (e) {
        formFieldCount++;
        ToggleMenus(true);
    });

    // listen for when an item is removed from the form
    document.addEventListener("fieldRemoved", function (e) {
        formFieldCount--;

        if (formFieldCount &lt;= 0) {
            ToggleMenus(false);
        }
    });

    function ToggleMenus(enableOrNot) {
        var menuBar = $("#TopicMenu").kendoMenu().data("kendoMenu");
        menuBar.enable("li:eq(0)", enableOrNot); // Save
        menuBar.enable("li:eq(1)", enableOrNot); // Clear
        menuBar.enable("li:eq(2)", enableOrNot); // Preview
    }
    </text>)
</script>
```

Also I note, that you incorrectly use a JS minifiers, because the inline code is contained in attributes (`script` tags contains the embedded code).

In addition, you use the WebMarkupMin not for its intended purpose. JS and CSS minifier-adapters are designed for use by the markup minifiers. If you just need a `CrockfordJsMinifier`, then use the [JSMin.NET](https://github.com/Taritsyn/JSMin.NET) library.

Henceforth, more carefully check your mistakes, so as not to take time away from other people.
