### ISSUE TITLE
Minification not working for tag like text

### ISSUE THREAD

**Issue by sreevishnu** [Taritsyn/WebMarkupMin#35]
Minification not working while loading user comments which looks like html tags.
For eg :` <p> Kesavan Namboothiri <kesav.pk> </p>`
I tried it  at http://webmarkupmin.apphb.com/minifiers/html-minifier
Is there any way to disable minification rather than throwing error ?

**Comment by Taritsyn** [comment]
Hello, Sreevishnu!

You need to escape the `<` and `>` characters:

```html
<p> Kesavan Namboothiri &lt;kesav.pk&gt; </p>
```

Also I recommend you to read the discussion of [“drop minification in case of errors”](https://github.com/Taritsyn/WebMarkupMin/issues/16) issue.

**Comment by sreevishnu** [comment]
Markup fixed the above issue for me. Thanks.
I have implemented custom logger called HtmlMinificationLogger which implements ILogger and added the following on startup(asp.net core 1.1)
`services.AddSingleton<WebMarkupMin.Core.Loggers.ILogger, HtmlMinificationLogger>();`
But still its showing error in case of parse errors. I tried NullLogger too. It should not show error, correct?

**Comment by Taritsyn** [comment]
Do you use WebMarkupMinMiddleware?

**Comment by sreevishnu** [comment]
Yes
`app.UseWebMarkupMin();`

**Comment by Taritsyn** [comment]
It's supposed to work. `services.AddSingleton<WebMarkupMin.Core.Loggers.ILogger, HtmlMinificationLogger>();` should go after the `services.AddWebMarkupMin();`.

**Comment by sreevishnu** [comment]
yup, its working now. Thank you very much Taritsyn :)
