### ISSUE TITLE
Skip minification on HTTP_PARSE_ERROR

### ISSUE THREAD

**Issue by mdzieg** [Taritsyn/WebMarkupMin#36]
Hi,

I am using minification in MVC5 project using attributes (ver. 2.3.0).
On some of the files we have HTML_PARSING_ERROR.
Desired behaviour is that minifier just skips such files rather than throwing an exception which results in 500.

There are two loggers available: null and exception.
I tried to remove exception logger but that what is below does not work:

`	<webMarkupMin xmlns="http://tempuri.org/WebMarkupMin.Configuration.xsd">
      <core>
         <logging defaultLogger="NullLogger">
            <loggers>
				<clear />
               <add name="NullLogger" displayName="Null Logger"
                  type="WebMarkupMin.Core.Loggers.NullLogger, WebMarkupMin.Core" />
            </loggers>
         </logging>
      </core>
   </webMarkupMin>`

**Comment by Taritsyn** [comment]
Hello, Mdzieg!

```xml
<webMarkupMin xmlns="http://tempuri.org/WebMarkupMin.Configuration.xsd">
  <core>
    <logging defaultLogger="NullLogger">
      <loggers>
        <clear />
        <add name="NullLogger" displayName="Null Logger" type="WebMarkupMin.Core.Loggers.NullLogger, WebMarkupMin.Core" />
      </loggers>
    </logging>
  </core>
</webMarkupMin>
```

It is configuration settings for version 1.X. I recommend you to read the following: 
[“How to upgrade applications to version 2.X”](https://github.com/Taritsyn/WebMarkupMin/wiki/How-to-upgrade-applications-to-version-2.X) and [“drop minification in case of errors”](https://github.com/Taritsyn/WebMarkupMin/issues/16).
