### ISSUE TITLE
Removing Body and Head Closing Tags

### ISSUE THREAD

**Issue by ghost** [Taritsyn/WebMarkupMin#37]
Hi,
I'm using this excellent library for a asp.net core 1.1 project. 

My Startup configuration are like below.
`
services.AddWebMarkupMin(opt =>
            {
                opt.AllowMinificationInDevelopmentEnvironment = true;
            }).AddHtmlMinification(options =>
            {
                options.MinificationSettings.RemoveRedundantAttributes = true;
                options.MinificationSettings.RemoveHttpProtocolFromAttributes = true;
                options.MinificationSettings.RemoveHttpsProtocolFromAttributes = true;
            });
`

Problem that I am facing is after the compression, there aren't any </body> or </html> tag.

**Comment by ghost** [comment]
options.MinificationSettings.**RemoveOptionalEndTags** = false;

Solved problem.

**Comment by Taritsyn** [comment]
Hello, Cihadsevim!

I recommend you also read about the `PreservableOptionalTagList` property in the [“HTML Minifier”](https://github.com/Taritsyn/WebMarkupMin/wiki/HTML-Minifier) section of  documentation.
