### ISSUE TITLE
Please Support javascript obfuscator

### ISSUE THREAD

**Issue by Hatef-Rostamkhani** [Taritsyn/WebMarkupMin#38]
Hi Dear
Please Support obfuscate javascript like [https://github.com/javascript-obfuscator/javascript-obfuscator](https://github.com/javascript-obfuscator/javascript-obfuscator)

Online version [https://javascriptobfuscator.herokuapp.com/](https://javascriptobfuscator.herokuapp.com/)

This is very useful but i can not use it in mvc. i want call it dynamically or set it on bundle js in mvc.

thank you so much

**Comment by Taritsyn** [comment]
Hello, Hatef!

This functionality is not needed by a wide range of users. You can create a JS minifier-adapter yourself by implementing the <code title="WebMarkupMin.Core.IJsMinifier">IJsMinifier</code> and <code title="WebMarkupMin.Core.IJsMinifierFactory">IJsMinifierFactory</code> interfaces.
