### ISSUE TITLE
WebMarkupMin.AspNet4.Mvc: Appear a strange string and disorder html tags

### ISSUE THREAD

**Issue by fioenix** [Taritsyn/WebMarkupMin#4]
Please help me,

I use WebMarkupMin.AspNet4.Mvc with default configurations.

After the browser rendered, the position of html tags disordered:

![screenshot_1](https://cloud.githubusercontent.com/assets/3040087/13942363/4e4a3162-f024-11e5-9857-711023bf6f9e.png)

**Comment by Taritsyn** [comment]
Hello, Fioenix!

Give an example of a HTML code before minification.

**Comment by Taritsyn** [comment]
I'm closing this error, because didn't get example of the HTML code before minification.

**Comment by fioenix** [comment]
Sorry, I'm late.

This is HTML code file.

Thanks & regards.

[Internet Tivi Sony 40 inch KDL-40W700C.txt](https://github.com/Taritsyn/WebMarkupMin/files/189138/Internet.Tivi.Sony.40.inch.KDL-40W700C.txt)

**Comment by Taritsyn** [comment]
Hello, Fioenix!

Did you tested this file? I have not found any `"&#65279"` strings in minified HTML code.

Why source file contains the following code:

```
<!-- saved from url=(0044)http://www.dmx.com/tivi/led-sony-kdl-40w700c -->
```

You saved it by using the browser? When saving an HTML document in this way, browser modifies its source code.

In addition, encoding declared 2 times:

```
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
```

**Comment by Taritsyn** [comment]
What version of the WebMarkupMin.Core are you using?

HTML entity `&#65279` is BOM. In [WebMarkupMin 2.0.0 RC 2](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.0.0-rc.2) solved this problem.

**Comment by fioenix** [comment]
Thank you very much for your support!

I used ASP.Net 4.5 (C#) & WebMarkupMin.Core.2.0.0-rc1, but after updated to RC2 I still saw this error.

I also removed duplicate meta tags.

This is original HTML code (not saved by the browser):
[Internet.Tivi.Sony.40.inch.KDL-40W700C.txt](https://github.com/Taritsyn/WebMarkupMin/files/198953/Internet.Tivi.Sony.40.inch.KDL-40W700C.txt)

Could you please help me to check if having any mistake?

**Comment by Taritsyn** [comment]
In this file not found problem.

You can check this, if you create the following action of controller:

``` csharp
[MinifyHtml]
public ActionResult Dmx()
{
    return new FileContentResult(
        System.IO.File.ReadAllBytes(@"C:\tmp\Internet.Tivi.Sony.40.inch.KDL-40W700C.txt"), "text/html");
}
```
