### ISSUE TITLE
Cannot capture the exception from minify html

### ISSUE THREAD

**Issue by thanh-nt-niteco** [Taritsyn/WebMarkupMin#44]
I got "Category: HTML_PARSING_ERROR" when using minify html. 
Normally it works fine, but in this case the html content is not valid, so that I got this exception.
But the content of website is from a cms so that sometime the html content won't be valid.

So that I want to capture this type of exception, and if it happens, I want to use the original html content instead of the minified version. Or I want the library to ignore this case during minifying.

Can I do it now? Or can you give me an advice for this case?
Thanks,

**Comment by Taritsyn** [comment]
Hello!

I recommend you to read the discussion of [“drop minification in case of errors”](https://github.com/Taritsyn/WebMarkupMin/issues/16) issue.

**Comment by thanh-nt-niteco** [comment]
Hello,
Thanks for your reply.
I will check it and let you know if I need any help.

**Comment by thanh-nt-niteco** [comment]
Here is the config I added to the web.config:
`<configSections>
        <sectionGroup name="webMarkupMin">
            <section name="core"
               type="WebMarkupMin.Core.Configuration.CoreConfiguration, WebMarkupMin.Core" />
        </sectionGroup>
    </configSections>
    <webMarkupMin xmlns="http://tempuri.org/WebMarkupMin.Configuration.xsd">
        <core>
            <logging defaultLogger="ThrowExceptionLogger">
                <loggers>
                    <add name="NullLogger"
                       displayName="Null Logger"
                       type="WebMarkupMin.Core.Loggers.NullLogger, WebMarkupMin.Core" />
                </loggers>
            </logging>
        </core>
    </webMarkupMin>`

And I am using WebMarkupMin.AspNet4.Mvc:
`
[MinifyHtml]
public class ContentController{}
`

But the exception is  still throwed, are there something I did wrong?

**Comment by Taritsyn** [comment]
It is configuration settings for version 1.X. I recommend you to read the [“How to upgrade applications to version 2.X”](https://github.com/Taritsyn/WebMarkupMin/wiki/How-to-upgrade-applications-to-version-2.X) section of documentation.

**Comment by thanh-nt-niteco** [comment]
it works properly.
Thanks,
