### ISSUE TITLE
DisableCompression And DisableMinification for MVC Action

### ISSUE THREAD

**Issue by astalegale** [Taritsyn/WebMarkupMin#45]
I'm using Compression and Minifying thru GlobalFilters in MVC.

Is it possibile to disable Minifying for some Actions?

Like:
[WebMarkupMin (DisableCompression = true, DisableMinification = true )]
public ActionResult FooAction ()
{
return View();
}

Thanks
Alex

**Comment by Taritsyn** [comment]
Hello!

> Is it possibile to disable Minifying for some Actions?

Yes it's possible, but this is done in a different way. Read about the `IncludedPages` and `ExcludedPages` properties in the [“ASP.NET Extensions > WebMarkupMin сommon configuration > Managers and options”](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-Extensions#managers-and-options) section of documentation. You may also need to read the [“ASP.NET 4.X Extensions”](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-4.X-Extensions) section.

**Comment by astalegale** [comment]
Thanks @Taritsyn , 

i've really missed that section!

Thanks a lot for the help!
