### ISSUE TITLE
HtmlMinificationModule with conditions?

### ISSUE THREAD

**Issue by LucGosso** [Taritsyn/WebMarkupMin#46]
Hi there! 

Is there a way of not minify on parts of the aspnet MVC 5 web? 

The CMS manager for Episerver is not working properly when their html is been minified. 

Is this configurable someway? 

My config today: 

` 
<modules runAllManagedModulesForAllRequests="true"> 
<add name="HtmlMinificationModule" type="WebMarkupMin.AspNet4.HttpModules.HtmlMinificationModule, WebMarkupMin.AspNet4.HttpModules" /></modules>`

**Comment by LucGosso** [comment]
I have tried 
`  <location path="cms">
    <system.webServer>
      <modules runAllManagedModulesForAllRequests="true">        
        <remove name="HtmlMinificationModule" />
      </modules>
    </system.webServer>
</location>`

with no luck...

**Comment by Taritsyn** [comment]
Hello, Luc!

I recommend you to read the following sections of the documentation: [“Ignoring fragments of markup”](https://github.com/Taritsyn/WebMarkupMin/wiki/Ignoring-fragments-of-markup), [“HTML Minifier”](https://github.com/Taritsyn/WebMarkupMin/wiki/HTML-Minifier), [“ASP.NET Extensions”](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-Extensions), [“ASP.NET 4.X Extensions”](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-4.X-Extensions) and [“WebMarkupMin: ASP.NET 4.X MVC”](https://github.com/Taritsyn/WebMarkupMin/wiki/WebMarkupMin:-ASP.NET-4.X-MVC).

**Comment by Taritsyn** [comment]
> `<location path="cms">…`

It is possible, that you will need to read only the [“ASP.NET Extensions > WebMarkupMin сommon configuration > Managers and options”](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-Extensions#managers-and-options) subsection.

**Comment by LucGosso** [comment]
Thanks for guidance... 

This did it:
HtmlMinificationManager.Current.ExcludedPages.Add(new WildcardUrlMatcher("/cms/*"));
