### ISSUE TITLE
Faced HTML_PARSING_ERROR while minifying

### ISSUE THREAD

**Issue by developer-amit-yadav** [Taritsyn/WebMarkupMin#47]
I am using WebMarkupMin extension and during HTML minification on release mode, I am facing an issue wherein i have used some code that conflicts with the minification process and returns an error that the <div> tag doesn't recognize the particular attribute.
So can i modify the extension to bypass a particular attribute. Or Even exclude the page from minification.

This is the code that is conflicting with the minification process.
`<div v-if="IsEditMode" class="btn btn-border" style="margin-right:16px" @click="toggleReorder();" title="Reorder">
                    <asp:Literal ID="Literal1" runat="server" Text="<%$Resources:Resource,Reorder %>"></asp:Literal>
				</div>`
Please guide me through this issue. Any help would be highly appreciated.

Please find the attached screen shot for Reference.
![webmarkupminissue](https://user-images.githubusercontent.com/33113086/32037637-cd8fc758-ba43-11e7-914f-08df0a444442.PNG)

**Comment by developer-amit-yadav** [comment]
This is the WebMarkupMin extension I am using WebMarkupMin.WebForms -Version 1.1.0

and this is the webconfig code.
`<webMarkupMin xmlns="http://tempuri.org/WebMarkupMin.Configuration.xsd">
		<core>
			<css>
				<minifiers>
					<add name="NullCssMinifier" displayName="Null CSS Minifier" type="WebMarkupMin.Core.Minifiers.NullCssMinifier, WebMarkupMin.Core" />
					<add name="KristensenCssMinifier" displayName="Mads Kristensen's CSS minifier" type="WebMarkupMin.Core.Minifiers.KristensenCssMinifier, WebMarkupMin.Core" />
				</minifiers>
			</css>
			<js>
				<minifiers>
					<add name="NullJsMinifier" displayName="Null JS Minifier" type="WebMarkupMin.Core.Minifiers.NullJsMinifier, WebMarkupMin.Core" />
					<add name="CrockfordJsMinifier" displayName="Douglas Crockford's JS Minifier" type="WebMarkupMin.Core.Minifiers.CrockfordJsMinifier, WebMarkupMin.Core" />
				</minifiers>
			</js>
      <html whitespaceMinificationMode="Medium" removeHtmlComments="true"
            removeHtmlCommentsFromScriptsAndStyles="true"
            removeCdataSectionsFromScriptsAndStyles="true"
            useShortDoctype="true" useMetaCharsetTag="false"
            emptyTagRenderMode="NoSlash" removeOptionalEndTags="true"
            removeTagsWithoutContent="false" collapseBooleanAttributes="true"
            removeEmptyAttributes="true" attributeQuotesRemovalMode="Html5"
            removeRedundantAttributes="false"
            removeJsTypeAttributes="true" removeCssTypeAttributes="true"
            removeHttpProtocolFromAttributes="false"
            removeHttpsProtocolFromAttributes="false"
            removeJsProtocolFromAttributes="false"
            minifyEmbeddedCssCode="true" minifyInlineCssCode="true"
            minifyEmbeddedJsCode="true" minifyInlineJsCode="true"
            processableScriptTypeList="" minifyKnockoutBindingExpressions="false"
            minifyAngularBindingExpressions="false" customAngularDirectiveList="" />
			<logging>
				<loggers>
				  <add name="NullLogger" displayName="Null Logger" type="WebMarkupMin.Core.Loggers.NullLogger, WebMarkupMin.Core" />
				  <add name="ThrowExceptionLogger" displayName="Throw exception logger" type="WebMarkupMin.Core.Loggers.ThrowExceptionLogger, WebMarkupMin.Core" />
				</loggers>
			</logging>
		</core>
  <webExtensions enableMinification="true" disableMinificationInDebugMode="true"
         enableCompression="true" disableCompressionInDebugMode="true"
         maxResponseSize="100000" disableCopyrightHttpHeaders="true" />
	</webMarkupMin>`

**Comment by developer-amit-yadav** [comment]
I contacted the Developer who made the code that is conflicting. Custom tags have been used in the code.
I searched and found out about HTML minification manager and exclude pages property.

Can you please provide a template as to where and how to use this property in asp.net 4.6.1 project.

**Comment by Taritsyn** [comment]
> This is the code that is conflicting with the minification process.
`<div … @click="toggleReorder();" …>`

Problems with similar attributes was solved in versions [1.1.0](https://webmarkupmin.codeplex.com/releases/view/620802) and [2.0.0 RC 6](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.0.0-rc.6). You need to update the WebMarkupMin.

> I searched and found out about HTML minification manager and exclude pages property.

This feature is only available in version 2.X. I recommend you to read the [“How to upgrade applications to version 2.X”](https://github.com/Taritsyn/WebMarkupMin/wiki/How-to-upgrade-applications-to-version-2.X) section of documentation. Also, see the [“drop minification in case of errors”](https://github.com/Taritsyn/WebMarkupMin/issues/16) and [“Skip minification on HTTP_PARSE_ERROR”](https://github.com/Taritsyn/WebMarkupMin/issues/36) discussions.

**Comment by developer-amit-yadav** [comment]
About the ASP.NET Extensions for the WebMarkupMin requires WebMarkupMin Common package.
But when i install this package all existing packages get disturbed and all settings in webconfig get replaced. So is there any particular order in which we have to install these packages so that they dont override each other.
I need webforms extension as our project is based on asp.net 4.6.1 alongwith commons.


Thanks for your quick reply i will check out the suggestions and reply here.

**Comment by Taritsyn** [comment]
> About the ASP.NET Extensions for the WebMarkupMin requires WebMarkupMin Common package.
But when i install this package all existing packages get disturbed and all settings in webconfig get replaced. So is there any particular order in which we have to install these packages so that they dont override each other.
>
> I need webforms extension as our project is based on asp.net 4.6.1 alongwith commons.

I highly recommend you to read the [“How to upgrade applications to version 2.X”](https://github.com/Taritsyn/WebMarkupMin/wiki/How-to-upgrade-applications-to-version-2.X) section of documentation.

**Comment by developer-amit-yadav** [comment]
Hi Taritsyn,
Sorry for bothering you so much... I went through the documentation and have figured out which classes i need to use to configure the WebMarkupMin extension like the HtmlMinificationSettings class for the setting that i had been using in the webconfig.
But the crucial part that where i have to use this code , If i have to minify all the aspx pages at runtime in the entire project.
Do i have to override the master page and other project pages by the classes of WebMarkupMin (MinifiedAndCompressedHtmlPage)  found in the WebMarkupMin.AspNet4.WebForms extension?
Can you please guide me through. 
Thanks for your help this all time.

**Comment by Taritsyn** [comment]
Hello, Amit!

> Sorry for bothering you so much...

I can not retell the contents of [documentation](https://github.com/Taritsyn/WebMarkupMin/wiki) to each user, because I just might not have enough free time.

> Do i have to override the master page and other project pages by the classes of WebMarkupMin (MinifiedAndCompressedHtmlPage) found in the WebMarkupMin.AspNet4.WebForms extension?

There is little, that has changed compared to version 1.X. Only a package name and namespace changed, rest remains the same (about this is written in the [“How to upgrade applications to version 2.X > ASP.NET 4.X Extensions > Web Forms”](https://github.com/Taritsyn/WebMarkupMin/wiki/How-to-upgrade-applications-to-version-2.X#web-forms) subsection). More information about this extension can be found in the [“WebMarkupMin: ASP.NET 4.X Web Forms”](https://github.com/Taritsyn/WebMarkupMin/wiki/WebMarkupMin:-ASP.NET-4.X-Web-Forms) section of documentation.

**Comment by developer-amit-yadav** [comment]
Hi Taritsyn,
Got the extension to work for the project. thanks for the help and for the extension too.

**Comment by Taritsyn** [comment]
Then close this issue.
