### ISSUE TITLE
ASP.NET Core 2 middleware error handling

### ISSUE THREAD

**Issue by madskristensen** [Taritsyn/WebMarkupMin#48]
When the HTML is malformed leading to an HTML parse error inside the WebMarkupMin middleware, there is no way to gracefully handle it. 

**Repro steps**
1. Add the WebMarkupMin middleware and verify it minifies the response HTML
2. Add an unclosed `<br` tag anywhere on the page 
3. Refresh the browser

**Actual**
The middleware throws an exception and the page is therefore not shown - but instead an error message is displayed if no custom error page is defined.

**Expected**
When an error occurs, simple just about the minification and serve the unminified. That way the page isn't broken and the user can see the content

**Comment by Taritsyn** [comment]
Hello, Mads!

This issue has been discussed many times (for example, [“drop minification in case of errors”](https://github.com/Taritsyn/WebMarkupMin/issues/16)). Just nobody reads the [documentation](https://github.com/Taritsyn/WebMarkupMin/wiki/Loggers).

**Comment by madskristensen** [comment]
I did read it, but I don't know how to use the NullLogger. Any code samples?

**Comment by madskristensen** [comment]
The NullLogger fixes the issue with the original repro step. However, add the following to any HTML reponse and it breaks again:

`<?xml:namespace prefix />`

**Comment by madskristensen** [comment]
Also, another issue with the `NullLogger` is that it disables logging for everything in the application and not just WebMarkupMin. How about adding a Boolean property to the service options called something like `options.ContinueOnError = true`

**Comment by madskristensen** [comment]
Never mind. I got confused by the names `ILogger` and `NullLogger` which both exist in a MS nuget package

**Comment by Taritsyn** [comment]
Hello, Mads!

> `<?xml:namespace prefix />`

This error is handled correctly.

> I got confused by the names `ILogger` and `NullLogger` which both exist in a MS nuget package

Unfortunately, I began to use such type names still in 2013.

> **Expected**
> When an error occurs, simple just about the minification and serve the unminified. That way the page isn't broken and the user can see the content

In next release I will make `NullLogger` the logger by default.
