### ISSUE TITLE
How to use WebMarkupMin in JavaScriptServices (React template)?

### ISSUE THREAD

**Issue by thangchung** [Taritsyn/WebMarkupMin#49]
Hi admin,

I have a very quick question that can I use this lib to minimize the up-front HTML size in the project using [JavaScriptServices](https://github.com/aspnet/JavaScriptServices) - React/Redux template? If I can, could you show me how? My project is at https://github.com/thangchung/blog-core/tree/master/src/Hosts/BlogCore.App
Thank you in advance.

**Comment by Taritsyn** [comment]
Hello!

Have you tried to use the [WebMarkupMin.AspNetCore2](https://www.nuget.org/packages/WebMarkupMin.AspNetCore2/) package? If you did not use this package, then read the following sections of documentation: [“ASP.NET Extensions”](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-Extensions),  [“WebMarkupMin: ASP.NET Core 1.X”](https://github.com/Taritsyn/WebMarkupMin/wiki/WebMarkupMin:-ASP.NET-Core-1.X) and [“WebMarkupMin: ASP.NET Core 2.X”](https://github.com/Taritsyn/WebMarkupMin/wiki/WebMarkupMin:-ASP.NET-Core-2.X).

Immediately I warn, that the WebMarkupMin can not minify the JSX code, only the output HTML code.

**Comment by thangchung** [comment]
@Taritsyn Thank you for your guidance. I will have a look at that documetation. Cheers!
