### ISSUE TITLE
Html Parsing Error. Message: Remain not closed conditional comment.

### ISSUE THREAD

**Issue by wderoo** [Taritsyn/WebMarkupMin#5]
When using MinifyHtml or MinifyXhtml i'm getting the following error.

Server Error in '/' Application.
![error html parser](https://cloud.githubusercontent.com/assets/1765029/13946429/dbc4e754-f014-11e5-8851-70db18d83e04.jpg)

Category: HTML_PARSING_ERROR
Message: Remain not closed conditional comment.

Using it in combination with Umbraco and MVC in a default controller.

```
public class DonutCacheController : RenderMvcController
{
    //[DonutOutputCache(Duration = 0, VaryByCustom="url;preview")]
    [CookieConsent]
    [CompressContent]
    [MinifyXhtml]
    [DonutOutputCache(CacheProfile = "CachSettings")]
    public override ActionResult Index(RenderModel model)
    {
        return base.Index(model);
    }        
}
```

It's probarly has to do someting with te picture element and IE9 if conditon statement in the html.
Source code html when the MinifyHtml is disabled.
[homepage.html.txt](https://github.com/Taritsyn/WebMarkupMin/files/183791/homepage.html.txt)

On some pages the error not occures.
[textpage.html.txt](https://github.com/Taritsyn/WebMarkupMin/files/183787/textpage.html.txt)

**Comment by Taritsyn** [comment]
Error in the following code:

```
<!--[if IE 9]><video style="display: none;><![endif]-->
```

in `style` attribute missing closing quote.

**Comment by wderoo** [comment]
Thnx! Sorry about that!
