### ISSUE TITLE
Minification not working - config issue?

### ISSUE THREAD

**Issue by christopherdude** [Taritsyn/WebMarkupMin#50]
I'm sure this is something that I'm doing, however, implementing _either_ master or page compiles and runs fine, but doesn't do minification.  I plugged in the config and put it through global, but still nothing happens.  Clues?

**Comment by Taritsyn** [comment]
Hello, Christopher!

> I'm sure this is something that I'm doing, however, implementing either master or page compiles and runs fine, but doesn't do minification.

Most likely, your web application is in debug mode. See a the [“ASP.NET 4.X Extensions > WebMarkupMin configuration”](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-4.X-Extensions#webmarkupmin-configuration) subsection of documentation.

I recommend you read the following sections of documentation: [“ASP.NET Extensions”](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-Extensions), [“ASP.NET 4.X Extensions”](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-4.X-Extensions) and [“WebMarkupMin: ASP.NET 4.X Web Forms”](https://github.com/Taritsyn/WebMarkupMin/wiki/WebMarkupMin:-ASP.NET-4.X-Web-Forms).

>  I plugged in the config and put it through global, but still nothing happens.

If you are still using version 1.X, then you should upgrade to version 2.X.  About how to do this, see the [“How to upgrade applications to version 2.X”](https://github.com/Taritsyn/WebMarkupMin/wiki/How-to-upgrade-applications-to-version-2.X) section of documentation.

**Comment by christopherdude** [comment]
Brilliant, that worked (debug).  I should have seen that.  Last question – does it minimize the WebResource.axd file, or is there a configuration / setting to ask it to?

**Comment by Taritsyn** [comment]
Hello, Christopher!

> Last question – does it minimize the WebResource.axd file, or is there a configuration / setting to ask it to?

As I understand, you did not read the [README.md](https://github.com/Taritsyn/WebMarkupMin/blob/master/README.md)? Web**Markup**Min minifies only markup of pages (HTML, XHTML and XML code). In addition, HTML and XHTML minifiers supports the minification of CSS code from `style` tags and attributes, and minification of JavaScript code from `script` tags, event attributes and hyperlinks with `javascript:` protocol.

Do not confuse the WebMarkupMin with the [WebOptimizer.NET](http://weboptimizer.codeplex.com/).

**Comment by christopherdude** [comment]
Yes, I read it and understood it.  But please understand that the WebResource.axd file produces a script tag with JavaScript contents, ergo my question regarding whether or not this tool minimizes the output.  It’s a legitimate question.

For example, if we know that a particular file with a particular extension (in this case WebResource.axd) always produces JavaScript, would it not be safe to ask whether or not this tool might be able to target such a specific file to let it know that it is a JavaScript file and that we are requesting that it will get minimized?  You stated that it does minification of JavaScript; this is indeed JavaScript.

However, what I believe you’re saying is that this tool can do minification of INLINE JavaScript, not JavaScript generated in separate files on the fly?

**Comment by Taritsyn** [comment]
> Yes, I read it and understood it. But please understand that the WebResource.axd file produces a script tag with JavaScript contents, ergo my question regarding whether or not this tool minimizes the output. It’s a legitimate question.

What media-type (`Content-Type`) have this the `WebResource.axd` file?

**Comment by Taritsyn** [comment]
> However, what I believe you’re saying is that this tool can do minification of INLINE JavaScript, not JavaScript generated in separate files on the fly?

Yes, only embedded and inline JavaScript code. Perhaps you need to try the [WebMarkupMin.AspNet4.HttpModules](https://github.com/Taritsyn/WebMarkupMin/wiki/WebMarkupMin:-ASP.NET-4.X-HTTP-modules) module instead of the WebMarkupMin.AspNet4.WebForms module. And then experiment with settings from the [“ASP.NET Extensions > Managers and options”](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-Extensions#managers-and-options) subsection of  documentation.

If you need to minify pure JavaScript code, then see the following libraries: [Microsoft Ajax Minifier](https://ajaxmin.codeplex.com/), [YUI Compressor for .Net](https://github.com/PureKrome/YUICompressor.NET), [NUglify](https://github.com/xoofx/NUglify) or [JSMin for .NET](https://github.com/Taritsyn/JSMin.NET).

**Comment by christopherdude** [comment]
I’m already minimizing all JS and CSS.  The problem is, the WebResource.axd creates JS on the fly.  I just need to interrupt that process and minimize before it outputs.  I’ll look into these below.  Thanks!
