### ISSUE TITLE
When Use   protected override void HandleUnknownAction(string actionName) ?

### ISSUE THREAD

**Issue by Hatef-Rostamkhani** [Taritsyn/WebMarkupMin#52]
Hi

When Use   
protected override void HandleUnknownAction(string actionName) 
and call
Index(model).ExecuteResult(this.ControllerContext);

my attribute not work 
[CompressContent]
[MinifyHtml]

also I register filtering like 
filters.Add(new CompressContentAttribute());
filters.Add(new MinifyHtmlAttribute());
filters.Add(new MinifyXmlAttribute());

can you help me for fix issue?
I need compress and minify HandleUnknownAction .

thanks

**Comment by Taritsyn** [comment]
Hello, Hatef!

When you call an action from the `HandleUnknownAction` method, then action filters are not applied. This is a limitation of framework.

I can only advise to replace the WebMarkupMin.AspNet4.Mvc module by the [WebMarkupMin.AspNet4.HttpModules](https://github.com/Taritsyn/WebMarkupMin/wiki/WebMarkupMin:-ASP.NET-4.X-HTTP-modules) module.

**Comment by Hatef-Rostamkhani** [comment]
Hello Taritsyn
I find solution.

if call this methods in HandleUnknownAction attribute do works

// for send pass model
**this.ControllerContext.RouteData.Values.Add("Model", model);**
// for execute normally and called attributes
**this.ActionInvoker.InvokeAction(this.ControllerContext, "Index");**
