### ISSUE TITLE
How to catch MinifyHtmlAttribute html_parsing_error exception

### ISSUE THREAD

**Issue by orizchak** [Taritsyn/WebMarkupMin#53]
I  a am using MinifyHtmlAttribute  on some of my actions, sometimes i get html_parsing_error exception,
then i go to my data and fix that problem.
The problem is that when this happen the page returning 500 until i fix the problem.
I would like an option to tell the MinifyHtmlAttribute  that if there was an error in minifing the html just log the error but dont take down the page, just return the page without minifying.

Is that possible ?

**Comment by Taritsyn** [comment]
Hello!

This issue has been discussed many times (for example, [“drop minification in case of errors”](https://github.com/Taritsyn/WebMarkupMin/issues/16)).

**Comment by orizchak** [comment]
Thanks
