### ISSUE TITLE
page is not minified by consecutive form post action

### ISSUE THREAD

**Issue by ghost** [Taritsyn/WebMarkupMin#54]
Hello Taritsyn,
I developed a simple ASP.NET MVC web site that has a form with several input text fields and a submit button.
When I first submit the form by clicking submit button, the form is posted to controller and generated html is successfully minified.
Then, I post the form again by submit button, generated html is not minified.
Then, I copy the url from the chrome browser address field and open new tab page in chrome, and paste url to the new tab page, the same page opens and its html is minified.
So, I think that WebMarkupMin has something problem with consecutive "form post" action.
If you have a good solution, please let me know.
I am using the following packages.

WebMarkupMin.AspNet.Common	2.4.0
WebMarkupMin.AspNet4.Common	2.4.0
WebMarkupMin.AspNet4.Mvc	2.4.0
WebMarkupMin.Core		2.4.0
WebMarkupMin.MsAjax		2.4.0
WebMarkupMin.Yui		2.4.0

**Comment by Taritsyn** [comment]
Hello, Hiromi!

Read in the [“ASP.NET Extensions > Managers and options”](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-Extensions#managers-and-options) subsection of documentation about the `SupportedHttpMethods` property.

**Comment by ghost** [comment]
Taritsyn,

Thank you for your quick reply.
I set the SupportedHttpMethods property to POST action and I could successfully minify the pages.
My Issue was solved!
Have a good day!
