### ISSUE TITLE
How to minify the JsRender templates in ASP.NET MVC?

### ISSUE THREAD

**Issue by arasu-rrk** [Taritsyn/WebMarkupMin#55]
I'm using a partial view in ASP.NET MVC. But the contents of these partial views not minified

`<div class="grid-container grid">
                    @Html.Partial("../Items/_ItemsGrid", new ViewDataDictionary { { "gridName", "datasources" } })
                </div>`

Is there any possibility to compress the partial views?

**Comment by Taritsyn** [comment]
Hello, Arasu!

I could not reproduce this error. You could make a demonstration project, which reproduce this error.

**Comment by arasu-rrk** [comment]
Hello @Taritsyn ,

Sorry for the confusion. It was not due to partial views. But we are using JsRender templates in our views. The response was not minified. Is it possible to minify this?

![image](https://user-images.githubusercontent.com/10368989/34521753-719ecb76-f0b5-11e7-81a5-ec418a7caf87.png)

**Comment by Taritsyn** [comment]
Compatibility with the JsRender is not guaranteed, but you can try to assign a value equals `text/x-jsrender` to the `ProcessableScriptTypeList` configuration property (see the [“HTML Minifier”](https://github.com/Taritsyn/WebMarkupMin/wiki/HTML-Minifier), [“ASP.NET Extensions”](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-Extensions) and [“ASP.NET 4.X Extensions”](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-4.X-Extensions) sections of documentation).
