### ISSUE TITLE
Breaks floating labels on Polymer's paper-input in Chrome.

### ISSUE THREAD

**Issue by bhelmore** [Taritsyn/WebMarkupMin#58]
When I use WebMarkupMin.Core (v2.4.0) to minify my Polymer project, the floating labels of my paper-input elements no longer work correctly in Chrome. Sometimes the label is initially in the floating (upper) state (even when the input has no value). Other times, it's not.  In either case, the floating label's position is not changed by editing the input's value. Oddly, the floating labels work fine in Firefox.

I created a simple page that contains a single paper-input with a label. The page references webcomponents-lite.js (not re-minfied) and imports paper-input.html. I minify paper-input.html and every file it references using WebMarkupMin server-side (using a custom .NET CORE FileProvider) and can see this issue.  Any help with this would be appreciated. Thanks!

SOLVED!

Setting MinifyEmbeddedCssCode to false seems to fix the issue.

**Comment by Taritsyn** [comment]
Hello!

> Setting MinifyEmbeddedCssCode to false seems to fix the issue.

What are you using a CSS minifier: `KristensenCssMinifier` or `NUglifyCssMinifier`?

I would be interested to see a CSS code, that causes this problem.

**Comment by bhelmore** [comment]
I'm doing this:
            MarkupMinificationResult result = new HtmlMinifier(
                new HtmlMinificationSettings()
                {
                    MinifyEmbeddedCssCode = false,
                }).Minify(strContents);

To see this problem, I'm simply minifying Google's stock paper-input element (and the components it references).  See https://www.webcomponents.org/element/PolymerElements/paper-input.

I'm guessing the problem is related to Polymer's CSS mixins. This is a CSS construct unique to Polymer. I'm guessing further that Chrome implements CSS mixins in its native code while Firefox probably relies on  a polyfill. That might explain why the problem is in Chrome and not in Firefox.

**Comment by Taritsyn** [comment]
Try to install the [WebMarkupMin.NUglify](https://www.nuget.org/packages/WebMarkupMin.NUglify/) package and modify your code as follows:

```csharp
…
using WebMarkupMin.NUglify;
…

MarkupMinificationResult result = new HtmlMinifier(cssMinifier: new NUglifyCssMinifier()).Minify(strContents);
```
