### ISSUE TITLE
Cannot minify HTML

### ISSUE THREAD

**Issue by bacvothanh** [Taritsyn/WebMarkupMin#59]
Hello!
I'm using Asp.net MVC 5, and WebMarkupMin.Mvc 1.1.0 , but there was a bug when to use MinifyHtmlAttribute,
Please help me resolve this bug!
![bug](https://user-images.githubusercontent.com/6470053/35499281-45b479da-0504-11e8-958a-29783b0c1e3b.png)

![bug1](https://user-images.githubusercontent.com/6470053/35499289-4ecc1604-0504-11e8-9dfb-70c7f9693f36.png)

**Comment by Taritsyn** [comment]
Hello!

Upgrade the WebMarkupMin to version 2.X. About how to do this, see the [“How to upgrade applications to version 2.X”](https://github.com/Taritsyn/WebMarkupMin/wiki/How-to-upgrade-applications-to-version-2.X) section of documentation.

**Comment by bacvothanh** [comment]
Thanks @Taritsyn , it resolved the bug, but it doesn't work correctly.
![bug2](https://user-images.githubusercontent.com/6470053/35501032-362fdd2c-050b-11e8-92bc-9a1a2531d4f2.png)
![bug3](https://user-images.githubusercontent.com/6470053/35501033-365df1bc-050b-11e8-8c23-b8ea0bd40b90.png)
![bug4](https://user-images.githubusercontent.com/6470053/35501078-6673ece4-050b-11e8-9c09-576267249350.png)

I don't know what I'm missing, please give me an advice!

**Comment by Taritsyn** [comment]
I recommend you to read the [“ASP.NET 4.X Extensions”](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-4.X-Extensions) section of documentation.

**Comment by Taritsyn** [comment]
Why did you installed the WebMarkupMin.AspNet4.HttpModules package?

**Comment by bacvothanh** [comment]
Hi @Taritsyn , thank you for your support!
The problem is resolved, it because I'm using mode debug, so that why it didn't work.
Let me summary the issue for someone meet it in the future :
- Upgrade to version 2.x
- Make sure compilation debug mode is "false"
Close the issue.
