### ISSUE TITLE
Incompatible with DeveloperExceptionPageMiddleware (ASP.NET 5)

### ISSUE THREAD

**Issue by justdmitry** [Taritsyn/WebMarkupMin#6]
In my `Startup.cs` I have `Configure` method like this:

```
app.UseIISPlatformHandler();
app.UseStaticFiles();
app.UseDeveloperExceptionPage();
app.UseIdentity()
app.UseRequestLocalization(...);
app.UseWebMarkupMin();
app.UseMvc(...);
```

I use `WebMarkupMin` only for MVC content (because all static files are already compressed/minified), but I want to use `DeveloperExceptionPageMiddleware` (`app.UseDeveloperExceptionPage()`) earlier in pipeline, because I want it to handle exceptions in identity/auth/... middleware too.

With this config, if any exception occurs (in MVC) - server returns blank page and I see exception in console window from DeveloperExceptionPageMiddleware:

> fail: Microsoft.AspNet.Diagnostics.DeveloperExceptionPageMiddleware[0]
>       An exception was thrown attempting to display the error page.
>       System.ArgumentException: Stream was not writable.
>          at System.IO.StreamWriter..ctor(Stream stream, Encoding encoding, Int32 bufferSize, Boolean leaveOpen)
>          at Microsoft.AspNet.Diagnostics.Views.BaseView.<ExecuteAsync>d__28.MoveNext()
>       --- End of stack trace from previous location where exception was thrown ---
>          at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>          at Microsoft.AspNet.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()

I guess this happens because `WebMarkupMin` already wrote compressed content (empty page?) into output response stream, and `DeveloperExceptionPageMiddleware` can't re-write this stream again.

Exception page shows successfully if I move `UseDeveloperExceptionPage()` after `UseWebMarkupMin()`, like this:

```
app.UseWebMarkupMin();
app.UseDeveloperExceptionPage();
app.UseMvc(...)
```

But I lose any details about exceptions in non-MVC middleware.

**Comment by justdmitry** [comment]
I tried to place `UseDeveloperExceptionPage()` immediately before `UseWebMarkupMin()` - problem still here, `DeveloperExceptionPageMiddleware` fails and error page not rendered. 

This means that other middleware (`UseIdentity`, `UseRequestLocalization`) are not "guilty".

**Comment by Taritsyn** [comment]
Hello, Dmitry!

In [WebMarkupMin 2.0.0 RC 5](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.0.0-rc.5) fixed this error.

Thanks for information!
