### ISSUE TITLE
WebMarkupMin minify even if disabled

### ISSUE THREAD

**Issue by Smit007i** [Taritsyn/WebMarkupMin#61]
Hello, Andrey!

I have the similar issue like https://github.com/Taritsyn/WebMarkupMin/issues/26
I am using  
WebMarkupMin.AspNet.Common	2.4.0.0
WebMarkupMin.AspNet4.Common 2.4.0.0
WebMarkupMin.AspNet4.Mvc 2.4.0.0
WebMarkupMin.Core 2.4.0.0
In my case the controllers are marked by [MinifyHtml] atts.
I've read almost all docs what you've sent before for similar cases. Then tried to change webExtensions section: DisableMinification = true, EnableMinification=false, maxResponseSize >-1, but it wasn't successful.

  

	<webMarkupMin xmlns="http://tempuri.org/WebMarkupMin.Configuration.xsd">
		<webExtensions DisableMinification="true" disableMinificationInDebugMode="false"
			 disableCompression="true" disableCompressionInDebugMode="false"
			 maxResponseSize="-1" disableCopyrightHttpHeaders="true" /> "
		core
			...
		/core
	</webMarkupMin>

Could you please help to correct config to disable Minifying?  

P.S.: It seems xmlns="http://tempuri.org/WebMarkupMin.Configuration.xsd" currently inavailable.

**Comment by Taritsyn** [comment]
Hello!

Completely upgrade the WebMarkupMin to version 2.X. About how to do this, see the [“How to upgrade applications to version 2.X”](https://github.com/Taritsyn/WebMarkupMin/wiki/How-to-upgrade-applications-to-version-2.X) section of documentation.

Then read the [“ASP.NET 4.X Extensions > WebMarkupMin configuration”](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-4.X-Extensions#webmarkupmin-configuration) subsection of documentation.

**Comment by Taritsyn** [comment]
Have you solved this problem?

**Comment by Smit007i** [comment]
Thank you, Andrey!
The problem is resolved.
