### ISSUE TITLE
Build failing - The request was aborted: Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by tyteen4a03** [Taritsyn/WebMarkupMin#62]
I can't build the solution with v2.4.2 with VS2017. It is failing to download KoreBuild from github with the error `The request was aborted: Could not create SSL/TLS secure channel`.

**Comment by Taritsyn** [comment]
Hello, Timothy!

It is better to try to build the last commit.

**Comment by tyteen4a03** [comment]
Might just have been my version of VS. Thanks!
