### ISSUE TITLE
The middleware blocks content streaming

### ISSUE THREAD

**Issue by alexanderm39** [Taritsyn/WebMarkupMin#63]
Hi

**Test code 1:**

    private static HttpClient Client { get; } = new HttpClient();
    [HttpGet]
    public async Task<FileStreamResult> Get()
    {
        var stream = await Client.GetStreamAsync("http://ipv4.download.thinkbroadband.com/1GB.zip");

        return new FileStreamResult(stream, new MediaTypeHeaderValue("application/octet-stream"))
        {
            FileDownloadName = "bigfile.zip"
        };
    }

**Test code 2:**

    public async Task Post()
    {
        var httpWriter = new StreamWriter(Response.Body);

        Response.ContentType = "text/event-stream";

        byte[] header = Encoding.ASCII.GetBytes("HELLO\n");

        await Response.Body.WriteAsync(header, 0, header.Length);

        await httpWriter.FlushAsync();

        try
        {
                await Run(httpWriter);
        }
        catch (Exception ex)
        {
            await httpWriter.WriteLineAsync(ex.ToString());
        }
    }

    private async Task Run(StreamWriter httpWriter)
    {
        for (int i = 0; i < 50; i++)
        {
            await httpWriter.WriteAsync($"data: {i}\n\n");
            await httpWriter.FlushAsync();
            await Task.Delay(300);
        }
    }

**Comment by Taritsyn** [comment]
Hello, Alex!

Thanks for information! This problem will require serious and long-term research.

But it seems to me, that the best variant for you would be to split your functionality into two web applications: user interface and streaming.

**Comment by Taritsyn** [comment]
Hello, Alex!

Try to upgrade to [version 2.4.4](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.4.4).
