### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by natiki** [Taritsyn/WebMarkupMin#64]
Hi,

I realise issues are being replied to so it does appear to be the case. Is the fact that the last release was in 7/05/2017 does it mean it is mostly in maintenance mode?

I see for instance NUglify is at 1.5.11 but this project only supports 1.5.6. Is the coupling that loose that external dependencies can be updated without concern?

**Comment by Taritsyn** [comment]
Hello, Donovan!

> Is the fact that the last release was in 7/05/2017 does it mean it is mostly in maintenance mode?

The [last release](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.4.2) was in 8/16/2017.

> I see for instance NUglify is at 1.5.11 but this project only supports 1.5.6

1.5.8

> Is the coupling that loose that external dependencies can be updated without concern?

Usually, Yes. But there are [exceptions](https://github.com/xoofx/NUglify/issues/29).

Unfortunately, now all my free time is spent on the development of third versions of the [JavaScript Engine Switcher](https://github.com/Taritsyn/JavaScriptEngineSwitcher) and [MSIE JavaScript Engine](https://github.com/Taritsyn/MsieJavaScriptEngine) libraries. After their release, I plan to develop this library.

Especially for you, I released a [version 2.4.3](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.4.3).

**Comment by natiki** [comment]
Awesome. Thanks for the info.
