### ISSUE TITLE
Inline JS No Semicolon Starts New Line

### ISSUE THREAD

**Issue by sobpilot** [Taritsyn/WebMarkupMin#65]
Is there a setting that will prevent starting a new line without the use of a semicolon using JS ES6?
Here is an example of the output.

```
return user}}});</script><template id=airport-card-template><div><v-card class=mb-1 v-bind:color=color> <v-card-text> <v-layout align-center wrap> <v-flex xs1 v-if=wait> <v-progress-circular indeterminate color=red></v-progress-circular> </v-flex> <v-flex v-if=flightRules><div><h3>{{wxdata.Info.IATA}} {{wxdata.Info.Name}} {{wxdata.Meta.Timestamp}}</h3><div><b>{{flightRules}}</b> {{wxdata.Translations.Clouds}}</div>Visibility: <b>{{wxdata.Translations.Visibility}}</b> Wind: <b>{{wxdata.Translations.Wind}}</b> Temperature: <b>{{wxdata.Translations.Temperature}}</b> Dewpoint: <b>{{wxdata.Translations.Dewpoint}}</b> Altimeter: <b>{{wxdata.Translations.Altimeter}}</b></div></v-flex> <v-flex v-if=!flightRules><h4>Loading Airport Information...</h4></v-flex> </v-layout> </v-card-text> </v-card></div></template><script>Vue.component("card-airport",{template:'#airport-card-template',props:["airportcode"],$_veeValidate:{validator:"new"},data:function(){return{wait:false,wxdata:{Info:{},Translations:{},Meta:{}},flightRules:null,airport:{status:{},weather:{meta:{}}}}},mounted(){this.Lookup()},computed:{color(){if(this.flightRules=="VFR")return"green white--text"
--
  | else if(this.flightRules==="IFR")return"red white--text"
  | else if(this.flightRules==="MVFR")return"yellow black--text"
  | else{return"grey lighten-2 black--text"}}},methods:{Lookup:function(){let wxurl="https://avwx.rest/api/metar/K"+
  | this.airportcode.toUpperCase()+"?options=info,translate"
  | axios.get(wxurl).then(response=>{this.wxdata=response.data
  | this.flightRules=this.wxdata["Flight-Rules"]
  | this.wait=false})}}})

```

**Comment by Taritsyn** [comment]
Hello!

Could you describe the problem more specifically?

Use the correct [Markdown code blocks](https://github.com/adam-p/Markdown-here/wiki/Markdown-Cheatsheet#code).

**Comment by sobpilot** [comment]
Using ES6 JS syntax does not require a semicolon at the end of each statement. The minified output of the lines without a semicolon starts a new line in the output. You can look at an example at [https://perdidosoft-airports.azurewebsites.net](url)

Notice in the generated source code view that instead of one single line output there are multiple lines.

Thanks for your help!

**Comment by Taritsyn** [comment]
Have you tried installing the [WebMarkupMin.NUglify](https://github.com/Taritsyn/WebMarkupMin/wiki/WebMarkupMin:-NUglify) module as an external JS minifier? You can try this module on the [WebMarkupMin Online](http://webmarkupmin.apphb.com/minifiers/html-minifier).

**Comment by sobpilot** [comment]
The only minifier I can get to work on ES6 code is Douglas Crockford's. I don't use any transpilers like Babel to keep the compile process simple.

**Comment by Taritsyn** [comment]
> The only minifier I can get to work on ES6 code is Douglas Crockford's. I don't use any transpilers like Babel to keep the compile process simple.

If the NUglify JS Minifier does not work correctly with ES6 code, then write about it to author of the [NUglify](https://github.com/xoofx/NUglify) library. You can also see the original settings of JS minifier ([CommonSettings.cs](https://github.com/xoofx/NUglify/blob/bc8d580adf319466261102ba0b1ffb6051e47f47/src/NUglify/CommonSettings.cs) and [CodeSettings.cs](https://github.com/xoofx/NUglify/blob/bc8d580adf319466261102ba0b1ffb6051e47f47/src/NUglify/JavaScript/CodeSettings.cs)).
