### ISSUE TITLE
WebMarkupMin not working with Fancybox

### ISSUE THREAD

**Issue by sipi41** [Taritsyn/WebMarkupMin#66]
Sorry to bother you but I think I found a bug which is actually, making me crazy! as no matter what I try, the result is the same.  

First, I would like to congratulate you for your minifier, is awesome! Second, I would love this awesome product to work fine with Fancybox.

When we don't use the minifier it works fine, but when the minifier is applied, no matter what options I use, fancybox can't show the content properly... it show the content but at the end of the page (very bottom)... according to them, this happens because each fancybox page should include the "<!doctype html>", I have checked via Chrome inspector, and yes, we have it... tried to change your options but nothing seems to work... I have included a copy of the project that you could run, when your plugin is enabled and when is not... please help!

[testWebApp.zip](https://github.com/Taritsyn/WebMarkupMin/files/2285126/testWebApp.zip)

**Comment by Taritsyn** [comment]
Hello, Guillermo!

Fancybox works only if there is a line break after the DOCTYPE directive, that is, it is not designed to work with a minified HTML code.

You have two variants:

1. Exclude the page from processing. In your case, you need to do this as follows:
```csharp
...
            ).AddHtmlMinification(
                op => {
                    op.ExcludedPages = new List<IUrlMatcher>() {
                        new ExactUrlMatcher("/Home/Test?fancybox=true")
...
```
2. Preserve content of view by using the [ignoring comment tags](https://github.com/Taritsyn/WebMarkupMin/wiki/Ignoring-fragments-of-markup).

When I close the [“Ability to provide your own whitespace removal strategy”](https://github.com/Taritsyn/WebMarkupMin/issues/27) issue, it will be easier to deal with such problems.

**Comment by Taritsyn** [comment]
Hello, Guillermo!

Try to upgrade to [version 2.5.1](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.5.1). And use the following code to preserve the line break:

```html
<!--wmm:ignore--><!DOCTYPE html>
<!--/wmm:ignore-->
```

**Comment by sipi41** [comment]
Taritsyn, thanks for your reply.  I did test using fancybox 2 and it works perfectly, not even need the <!DOCTYPE html>, of course we will eventually need to move forward. 

I tried to contact them about this but they blame me for that problem, and told me to post this to a live test environment... is this possible? how to? maybe creating a subdomain an publish all there... 

I will test your solution and will post my response soon... thanks for taking this into consideration.

**Comment by fancyapps** [comment]
@Taritsyn Why do you think that fancybox "is not designed to work with a minified HTML code"? As the author of this script, I am very, very surprised about such statement. I would like to hear some details or see some (live) demo.

**Comment by sipi41** [comment]
I will create a test subdomain with 3 versions and post here, probably this afternoon:

1. Html page with Fancybox Version 3+ without DOCTYPE directive (failure)
2. Html page with Fancybox 3+ with DOCTYPE directive (working)
3. Html page with Fancybox 3+ and Minifier plugin (failure)

So you can see what the result is.

**Comment by Taritsyn** [comment]
Hello, Jānis!

You can try WebMarkupMin HTML minifier in action and experiment with different minification settings live on the WebMarkupMin Online site - http://webmarkupmin.apphb.com/minifiers/html-minifier

**Comment by fancyapps** [comment]
Here is a minified bare bone demo of fancybox - https://fancyapps.com/tmp/doctype/ - and it works fine. So, I am asking again, what is the reason of your statement?

**Comment by Taritsyn** [comment]
@fancyapps The following code causes problems when you load it into a window:

```html
<!DOCTYPE html><p>Hola mundo!!!</p>
```

and this code works correctly:

```html
<!DOCTYPE html>
<p>Hola mundo!!!</p>
```

**Comment by sipi41** [comment]
let me create the samples first, so he can analyze them... as with the code he uploaded all seems to work fine.

**Comment by fancyapps** [comment]
> The following code causes problems when you load it into a window

What do you mean by "load it into a window"? I updated the demo with that snippet and it still works fine (as expected).

**Comment by Taritsyn** [comment]
I think that Guillermo will explain it better.

**Comment by fancyapps** [comment]
Maybe this is something related to .net? Sorry, I am not familiar with that. I know that some developers are using `parentEl` option to customize location of container, e.g., doing something like this:

`$.fancybox.defaults.parentEl = "form:first" `.

**Comment by sipi41** [comment]
basically .net core (in this case) should produce nothing else than pure html/javascript/css... nothing weird...

**Comment by sipi41** [comment]
Ok, I have the samples, all of them are very simple... have a landing page which loads jquery and fancybox with a button, when clicking the button it calls "/Home/Test" which is the content we want to show into the fancybox window... 

1. http://sample1.hispaniamedia.com/ The first sample runs **minified, using fancybox 2**.  runs smoothly!

2. http://sample2.hispaniamedia.com/ The second show the same example, this time using **fancybox 3, is not minified** in any way BUT the fancybox window content **does not include the `<!doctype html>`**  directive, as you can see it does not display the content properly but way at the bottom.

3. http://sample3.hispaniamedia.com/ The third, shows a **no-minified** version but this time we **included the `<!doctype html>` directive** (on /Home/Test of course, which is the ajax source) and it seems to work fine.

4. http://sample4.hispaniamedia.com/ This one shows a **minified version with the `<!doctype html>` directive**, unfortunately it behaves like the number 2, but the directive is there... this is why @Taritsyn was mentioning he did a test and found that the problem arises when they remove the new line character at the end of the directive while they minify.

I want to point to some extra information:

- The test was made on https and http
- The test was made on mozilla firefox, chrome and edge, behavior is the same.
- Other tests were made by me: for example, I did configure the minifier to NOT TO remove quotes, not to remove closing tags (that you may notice missing, for example, there's no `</head>` or `</body>` and so on... the result is the same.

Thank you for your time, please let me know what do you think.

**Comment by Taritsyn** [comment]
Need a fifth sample with installed the WebMarkupMin.Core 2.5.1 and preserved DOCTYPE with line break:

```html
<!--wmm:ignore--><!DOCTYPE html>
<!--/wmm:ignore-->
```

**Comment by sipi41** [comment]
@Taritsyn let me work on that... I'll post when done. Thanks.  Did you be able to reproduce the issues as described?

**Comment by Taritsyn** [comment]
Yes, I've tried all variants except for the fancybox 2. I made a fifth sample and everything works for me.

**Comment by sipi41** [comment]
@Taritsyn I did not upload the 5th sample because locally, even if we add the changes you requested, it shows the same bad behavior, I did notice that `<!--wmm:ignore-->` labels are still there also.

**Comment by fancyapps** [comment]
OK, thanks for the demos! As it turns out, this issue is not related to the minifier at all. 
Thanks @Taritsyn for your time and sorry for the trouble, you can close this issue.

**Comment by Taritsyn** [comment]
@sipi41

> I did not upload the 5th sample because locally, even if we add the changes you requested, it shows the same bad behavior,...

Need to install the WebMarkupMin.Core 2.5.1.

> I did notice that  labels are still there also.

See the [“Ignoring fragments of markup”](https://github.com/Taritsyn/WebMarkupMin/wiki/Ignoring-fragments-of-markup) section of documentation.

**Comment by Taritsyn** [comment]
@fancyapps OK, thanks.

**Comment by sipi41** [comment]
Thankyou @Taritsyn  and @fancyapps, it was a problem with Fancybox, the solution was to wrap the whole content into a `<DIV>` tag, I mean, the content shown on the Fancybox popup window.
