### ISSUE TITLE
Compression in Release mode

### ISSUE THREAD

**Issue by rcausier** [Taritsyn/WebMarkupMin#67]
Hello,

I just tried your WebMarkupMin.AspNet4.Mvc 2.5.0 fantastic module.
I my development code, I installed the nugget package then I just add 1 line of code before my controller class "[CompressContent]".
I ran my code in DEBUG mode in Firefox and everything worked fine : the transfert size of my HTML page is 30kb instead of 200kb size.
Perfect !

So I decided to put my project in the production server (RELEASE mode then).
The page is not compressed (transfer size = html size).

Can you tell me id I need to configure something else (web.config, global.asax, IIS, ...) to make it work ?

Thanks a lot for your help !

**Comment by Taritsyn** [comment]
Hello!

See the [“ASP.NET 4.X Extensions > WebMarkupMin configuration”](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-4.X-Extensions#webmarkupmin-configuration) subsection of documentation.

**Comment by rcausier** [comment]
ok I saw this doc before writing to you
I thought I don't need these lines because it's already working in DEBUG mode

I only use the Compression function for the moment
so the only lines which seems useful are : 

            IHttpCompressionManager httpCompressionManager =
                HttpCompressionManager.Current;
            httpCompressionManager.CompressorFactories = new List<ICompressorFactory>
            {
                new BrotliCompressorFactory(),
                new DeflateCompressorFactory(),
                new GZipCompressorFactory()
            };

it is correct ?

thanks again for your answer

**Comment by Taritsyn** [comment]
Check the `Web.config` file on your server again. It should have the following setting::

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    …
    <system.web>
        …
        <compilation debug="false" … />
        …
    </system.web>
    …
</configuration>
```

**Comment by rcausier** [comment]
I have this : <compilation targetFramework="4.5" debug="false" />

**Comment by rcausier** [comment]
compilation targetFramework="4.5" debug="false"

**Comment by Taritsyn** [comment]
> I ran my code in DEBUG mode in Firefox and everything worked fine : the transfert size of my HTML page is 30kb instead of 200kb size.

It is very strange. Maybe the compression was made not by WebMarkupMin, but by IIS Express?

**Comment by Taritsyn** [comment]
I recommend you to make a demo project and check your settings on it.
