### ISSUE TITLE
sitemap.xml problem asp.net MVC

### ISSUE THREAD

**Issue by MarioPrograms** [Taritsyn/WebMarkupMin#7]
When there is a problem with the sitemap.xml file. instead of the xml file we get a strange value. When you turn off the compression everything returns to normal.
WebMarkupMin.AspNet4.Mvc

**Comment by Taritsyn** [comment]
See the discussion of similar problem - [“WebMarkupMin and HTML_PARSING_ERROR”](http://webmarkupmin.codeplex.com/workitem/22).

**Comment by Taritsyn** [comment]
You helped this information?

**Comment by Taritsyn** [comment]
I'm closing this error, because not receive feedback.
