### ISSUE TITLE
Html.Raw problem

### ISSUE THREAD

**Issue by NePheus** [Taritsyn/WebMarkupMin#71]
Hello Andrey,

I have a problem with WebMarkupMin when using the @Html.Raw() function in a razor file. Basically it works fine, also when the parameter has html tags inside. The problem starts when I just have something like @Html.Raw("<"). Then I just get an broken output of strange symbol. Do you have a solution for this or is this a bug in the lib?
Btw. the same problem occurs, if the content of a "o.MinificationSettings.ProcessableScriptTypeList" item contains a "<" that does not represent a html tag.

**Comment by Taritsyn** [comment]
Hello, Jan!

> The problem starts when I just have something like @Html.Raw("<").

This is incorrect code. You must replace the `<` symbol with `&lt;`. Check your non-minified code by using the [W3C Markup Validation Service](https://validator.w3.org/#validate_by_input).

**Comment by NePheus** [comment]
You are totally right. I think the problem is when I give the user an input field and allow HTML Code inside. So how could I prevent, that the user inputs something like:

`This is <b>important</b>. This is a less than (<) symbol.`

I just have simple input fields at this point, no WYSIWIG editor, that maybe would handle this problem.

The other example from the first post is a kendo template, where I can't use an if-statement with a '<' symbol inside.
I.e. `if (i < 5) {...}` results in the same problem as Html.Raw().
I know, you didn't recommend it https://github.com/Taritsyn/WebMarkupMin/issues/70, I just gave it a try, but I can live with it.

**Comment by Taritsyn** [comment]
> I just have simple input fields at this point, no WYSIWIG editor, that maybe would handle this problem.

The simplest way is to try to apply HTML minification before saving data and handle errors (show them in user interface). I recommend you to see an example from the [“Core &gt; Markup minifiers &gt; HTML Minifier”](https://github.com/Taritsyn/WebMarkupMin/wiki/HTML-Minifier) section of documentation. You can also use some HTML parser (for example, [Html Agility Pack](https://github.com/zzzprojects/html-agility-pack/) or [AngleSharp](https://anglesharp.github.io/)) for this purpose.

> I.e. if (i < 5) {...} results in the same problem as Html.Raw().

You should understand, that using the `ProcessableScriptTypeList` property, you specify the script types, which are processed as HTML.

**Comment by NePheus** [comment]
Ok, I will find a solution for this. Thank you very much for the fast reply.
