### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by bluetrees886** [Taritsyn/WebMarkupMin#72]
hi,
in html compress，when html label attrbute has a empty string, it will not be compressed correct.

for example: 
the label's data-options has a empty string
<input type="text" data-options="" name="xx" />
after compressed
<input type="text" data-options=name="xx" />

**Comment by bluetrees886** [comment]
hi,
in html compress，when html label attrbute has a empty string, it will not be compressed correct.
for example:
the label's data-options has a empty string
<input type="text" data-options="" name="xx" />
after compressed
<input type=text data-options=name=xx />

**Comment by Taritsyn** [comment]
Hello!

Thanks for information! This error is fixed in [version 2.5.4](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.5.4).
