### ISSUE TITLE
HtmlMinifier.Minify hangs permanently

### ISSUE THREAD

**Issue by Metalnem** [Taritsyn/WebMarkupMin#73]
**HtmlMinifier.Minify** hangs permanently when attempting to minify the file from the [attached archive]. You can run the following code to reproduce it (the **path** variable should contain the path to the extracted file):

```csharp
var text = File.ReadAllText(path);
new HtmlMinifier().Minify(text);
```

Found via [SharpFuzz].

[attached archive]: https://github.com/Taritsyn/WebMarkupMin/files/2707078/Test.zip
[SharpFuzz]: https://github.com/Metalnem/sharpfuzz

**Comment by Taritsyn** [comment]
Hello, Nemanja!

This error is fixed in [version 2.5.6](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.5.6). Thanks for information!
