### ISSUE TITLE
Provide events useful for testing and benchmarking

### ISSUE THREAD

**Issue by jxlarrea** [Taritsyn/WebMarkupMin#74]
I'm trying to figure out how much overhead WebMarkupMin adds to my ASP.NET Core 2 project. It would be useful to have some events/hooks/callbacks such as OnStart and OnFinish to measure the impact of the minimization process.

**Comment by Taritsyn** [comment]
Hello, Xavier!

Can you give an example of a popular .NET library, that uses a similar approach when implementing the ASP.NET Core middleware?

**Comment by jxlarrea** [comment]
Without going too far, the OAuth middleware itself. 

```
services.AddAuthentication(options =>
        {
            options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;            
        })
        .AddCookie()
        .AddOAuth("GitHub", options =>
        {
            options.ClientId = Configuration["GitHub:ClientId"];
            options.ClientSecret = Configuration["GitHub:ClientSecret"];
            options.CallbackPath = new PathString("/signin-github");

            options.Events = new OAuthEvents
            {
                OnCreatingTicket = async context =>
                {
                    var request = new HttpRequestMessage(HttpMethod.Get, context.Options.UserInformationEndpoint);
                    request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", context.AccessToken);

                    var response = await context.Backchannel.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, context.HttpContext.RequestAborted);
                    response.EnsureSuccessStatusCode();

                    var user = JObject.Parse(await response.Content.ReadAsStringAsync());

                    context.RunClaimActions(user);
                }
            };
        });
```

Not really used for benchmarking but it should give you an idea. 

The thing is that I would like to measure the performance of WebMarkupMin with different settings. Currently my implementation adds an additional 50ms to the pipeline which is significant considering that without it my full page render is around 30ms.

It would be great to have some events like OnBeforeHtmlMinification and OnAfterHtmlMinification. You could even pass the Statistics object you use for the logger in those events.

**Comment by Taritsyn** [comment]
You have not tried to implement your own [logger](https://github.com/Taritsyn/WebMarkupMin/wiki/Loggers), register it as a singleton service and enable the [generation of minification statistics](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-Extensions#html-minification-manager-and-options)?

If you need more information, then you can use a solution like the one described in the Jeff Putz's article [“ASP.NET Core middleware to measure request processing time”](https://weblogs.asp.net/jeff/asp-net-core-middleware-to-measure-request-processing-time).

**Comment by jxlarrea** [comment]
The problem with those 2 approaches is that there is no way to know *when* the WebMarkupMin middleware execution starts and ends, accurate measuring of performance would be merely guessing. 

Ideally, I would be using something like [MiniProfiler](https://github.com/MiniProfiler/dotnet) and hook it OnBeforeHtmlMinification and OnAfterHtmlMinification.

**Comment by Taritsyn** [comment]
The second way gives this opportunity:

```csharp
 …
app.Use(async (context, next) =>
{
    // Before processing…
    await next.Invoke();
    // After processing…
});

app.UseWebMarkupMin();

app.UseMvc(routes =>
{
    …
});
…
```

**Comment by jxlarrea** [comment]
I cannot see how would I measure how long it would take for **only** the WebMarkupMin middleware to execute in the above example.

Perhaps I'm missing something, could you please illustrate?

**Comment by Taritsyn** [comment]
You can simply compare performance with and without the WebMarkupMin.

**Comment by jxlarrea** [comment]
No words...

Thanks for the time, I guess.

**Comment by Taritsyn** [comment]
You can't always get what you want.
