### ISSUE TITLE
Unexpected result - Weird symbols

### ISSUE THREAD

**Issue by sipi41** [Taritsyn/WebMarkupMin#75]
Hi! first, thanks for your time.  I'm having a similar issue to https://github.com/Taritsyn/WebMarkupMin/issues/68.

Symptom: I'm getting bunch of weird symbols instead of html, please check the following image:

![screenshot](https://user-images.githubusercontent.com/688562/50661904-3c0dd400-0f6a-11e9-8ed6-059b8e878f24.png)

I'm using **WebMarkupMin.AspNetCore2 and WebMarkupMin.NUglify**; 

1. I noticed the behavior appear when calling the method "AddHttpCompression()".
2. It happens on protected pages by Identity, I mean, if I go to my main page where users login, the page display and compresses properly, once I click log-in, the problem arises.

I did read the issue 68, and it says something about the IIS compression / web.config but in this case, the IIS is express, and I'm not sure what are we looking there?

Please help!

**Comment by Taritsyn** [comment]
Hello, Guillermo!

It is difficult to say anything without looking at contents of the `Startup.cs` file.

**Comment by sipi41** [comment]
Hello @Taritsyn !  Here's a copy of my code on **Startup.cs**:

`using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using System.Diagnostics;
using TaxBookkeepingMarketing.Data;
using TaxBookkeepingMarketing.Models;
using WebMarkupMin.AspNetCore2;
using WebMarkupMin.NUglify;

namespace TaxBookkeepingMarketing
{
    public class Startup
    {

        private IConfiguration configuracion;

        public Startup(IConfiguration conf)
        {
            this.configuracion = conf;
        }

        public void ConfigureServices(IServiceCollection services)
        {

            services.AddWebMarkupMin(opciones =>
            {
                opciones.AllowMinificationInDevelopmentEnvironment = true;
                opciones.AllowCompressionInDevelopmentEnvironment = true;
            }).AddHtmlMinification(opciones =>
            {
                opciones.CssMinifierFactory = new NUglifyCssMinifierFactory();
                opciones.JsMinifierFactory = new NUglifyJsMinifierFactory();

            }).AddHttpCompression(opciones =>
            {

            });

            services.AddDbContext<AppDbContext>(
                opciones => { opciones.UseSqlServer(configuracion.GetConnectionString("DefaultConnection")); }
            );

            services.AddDbContext<AppIdentityDbContext>(
                opciones => opciones.UseSqlServer(configuracion.GetConnectionString("DefaultConnection")) 
            );

            services.AddIdentity<IdentityUser, IdentityRole>()
                .AddEntityFrameworkStores<AppIdentityDbContext>()
                .AddDefaultTokenProviders();

            services.AddScoped<IDeposito, Deposito>();

            services.AddMvc();

        }


        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {            

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseStatusCodePages();
            app.UseStaticFiles();           

            app.UseWebMarkupMin();

            app.UseAuthentication();

            

            app.UseMvc(
                routes => {
                    routes.MapRoute("default", "{controller=Account}/{action=Login}");
                }    
            );

        }
    }
}
`

**Comment by Taritsyn** [comment]
Did not try to interchange positions of the `app.UseWebMarkupMin()` and `app.UseAuthentication()` methods?

**Comment by sipi41** [comment]
it makes no difference, I did try that, change the order so I could see any difference but nothing, just the same thing.  As you can see, there's nothing weird on my code, just a regular app using mvc and authentication. Please help! :-(

**Comment by Taritsyn** [comment]
Try to reproduce this error in the form of demo project and send me a link to it.

**Comment by sipi41** [comment]
Excuse my ignorance but, how can I do that? I want to do it but I'm newbie :-(  I can make a zip and ship my project to you if you wish, I just need your external IP to open my database so you can run the project... would that work for you? We can also remote you into my PC so you can see and make tests...

**Comment by Taritsyn** [comment]
> ..., I just need your external IP to open my database so you can run the project...

I'm not technical support. I don't need your project from production.

Try to create a demo project, that reproduces this error, from scratch. And then publish the project as a zip archive on a service like the Dropbox and send me a link.

It is possible when you reproduce the error, you will find its cause.
