### ISSUE TITLE
How to minify only when attribute in action was set? 

### ISSUE THREAD

**Issue by ericfelipe99** [Taritsyn/WebMarkupMin#78]
I'm testing the performance of this minification for production, so, i need only some controllers to be minified. i see some actions's attributes to do that, but its not working... when i use configuration in global, all pages was minified, when i not use configuration none of pages are minified. 

```
        public static void RegisterGlobalFilters(GlobalFilterCollection filters)
        {
...
            //filters.Add(new CompressContentAttribute());
            filters.Add(new MinifyHtmlAttribute());
...
        }
```

```
  public class WebMarkupMinConfig
    {
        public static void Configure(WebMarkupMinConfiguration configuration)
        {
            

            configuration.AllowMinificationInDebugMode = true;
            configuration.AllowCompressionInDebugMode = true;

            configuration.DisableCompression = true;
            configuration.DisablePoweredByHttpHeaders = true;
            configuration.DisableMinification = false;
            
            IHtmlMinificationManager htmlMinificationManager =
                HtmlMinificationManager.Current;
            htmlMinificationManager.IncludedPages.Clear(); 
            htmlMinificationManager.ExcludedPages = new List<IUrlMatcher>
            {
                //new WildcardUrlMatcher("*"),
                //new ExactUrlMatcher("/contact")
            };

        }
```

Controller and attribute
```
    [ActionName("compress-js")]
        [WebMarkupMin.AspNet4.Mvc.MinifyHtml()]
        public ActionResult compressjs()
        {
            return View("compress-js");
        }
```

image of installed bundles. 

![image](https://user-images.githubusercontent.com/7040153/52874643-43afc380-3139-11e9-85b0-9635751b8b5c.png)

**Comment by Taritsyn** [comment]
Сannot use global filters and action filters at the same time, select one.

I also recommend to register [your own logger](https://github.com/Taritsyn/WebMarkupMin/wiki/Loggers) or use the `ThrowExceptionLogger` class to find problems:

```csharp
DefaultLogger.Current = new ThrowExceptionLogger();
```

By the way, this cleaning is not necessary:

```csharp
            htmlMinificationManager.IncludedPages.Clear();
```

What content  return the `compress-js` action?

**Comment by ericfelipe99** [comment]
> Сannot use global filters and action filters at the same time, select one.
> 
> I also recommend to register [your own logger](https://github.com/Taritsyn/WebMarkupMin/wiki/Loggers) or use the `ThrowExceptionLogger` class to find problems:
> 
> ```cs
> DefaultLogger.Current = new ThrowExceptionLogger();
> ```
> 
> By the way, this cleaning is not necessary:
> 
> ```cs
>             htmlMinificationManager.IncludedPages.Clear();
> ```
> 
> What content return the `compress-js` action?

Thanks for your reply. 

The action "compress-js" is an test of compression methods that i'm testing.... it's return our home page with some tries of components to get better performance. 

I reached the goal by manipulating the property "includedPages" and "ExcludedPages"... but with attributes in action don't worked to me. 

Thanks, i appreciate your help.

**Comment by Taritsyn** [comment]
> ... but with attributes in action don't worked to me.

In the [WebMarkupMin.Sample.AspNet4.Mvc4](https://github.com/Taritsyn/WebMarkupMin/tree/master/samples/WebMarkupMin.Sample.AspNet4.Mvc4) demo project it works.

**Comment by ericfelipe99** [comment]
> > ... but with attributes in action don't worked to me.
> 
> In the [WebMarkupMin.Sample.AspNet4.Mvc4](https://github.com/Taritsyn/WebMarkupMin/tree/master/samples/WebMarkupMin.Sample.AspNet4.Mvc4) demo project it works.

thanks, I will download and test. thanks. 

how to close this thread?

**Comment by Taritsyn** [comment]
> how to close this thread?

Use the “Close issue” button.

**Comment by ericfelipe99** [comment]
Thanks for help.
