### ISSUE TITLE
Add GrandNode to the README.md

### ISSUE THREAD

**Issue by PatrykPorabik** [Taritsyn/WebMarkupMin#79]
Hi,

We use WebMarkupMin in our open source e-commerce solution. We will be glad if you add it to the list of softwares in your readme file. 

Link to the project: https://github.com/grandnode/grandnode

**Comment by Taritsyn** [comment]
Hello, Patryk!

Thanks for information! I added your software product to the list.

**Comment by PatrykPorabik** [comment]
Great, thank you!
