### ISSUE TITLE
Unable to minify when using a custom compressor

### ISSUE THREAD

**Issue by aloksharma1** [Taritsyn/WebMarkupMin#83]
Hi,
when i use the documentation given for minification and webmarkupmin config in my mvc project like this:
```
         [DonutOutputCache(CacheProfile = "Public1Year")]
        [CompressContent]
        //[CommonClasses.MVCFilterAttributes.Compress]
        [MinifyHtml]
        [MinifyXml]
```

i get no issue/error and the page is showing, but when i switch to my own compression pipeline:

```
         [DonutOutputCache(CacheProfile = "Public1Year")]
         //[CompressContent]
        [CommonClasses.MVCFilterAttributes.Compress]
        [MinifyHtml]
        [MinifyXml]
```
i am getting error like these:

> Can not apply markup minification to text content, that was encoded in the 'br' format.

or
> Can not apply markup minification to text content, that was encoded in the 'gzip' format.

i even tried using Order Attribute to redefine execution sequence for attributes, but it didnt worked for me. like this :
```
         [DonutOutputCache(CacheProfile = "Public1Year")]
         //[CompressContent]
        [CommonClasses.MVCFilterAttributes.Compress(Order=2)]
        [MinifyHtml(Order=0)]
        [MinifyXml(Order=1)]
```

**Comment by Taritsyn** [comment]
Hello, Alok!

Just the `CommonClasses.MVCFilterAttributes.Compress` filter always performs processing before minification of markup. Write to the author of filter about this problem.

While replace it with the `CompressContent` filter. If you need Brotli support, then install the [WebMarkupMin.AspNet.Brotli](http://nuget.org/packages/WebMarkupMin.AspNet.Brotli/) module and register the `BrotliCompressorFactory` (see the documentation for [ASP.NET 4.X](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-4.X-Extensions#specificity-of-configuration) or [ASP.NET Core](https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-Core-1.X#specificity-of-configuration)).

**Comment by aloksharma1** [comment]
Hi,
thanks for prompt reply. that lib is custom made by me. so i am not sure how its affecting the execution order. the code is as simple as this:
```
public class CompressAttribute : ActionFilterAttribute
    {
        public override void OnActionExecuting(ActionExecutingContext filterContext)
        {

            var encodingsAccepted = filterContext.HttpContext.Request.Headers["Accept-Encoding"];
            if (string.IsNullOrEmpty(encodingsAccepted)) return;

            encodingsAccepted = encodingsAccepted.ToLowerInvariant();
            var response = filterContext.HttpContext.Response;
            response.Cache.SetExpires(DateTime.Now.AddYears(1));
            response.Cache.SetCacheability(HttpCacheability.Public);
            response.Cache.SetMaxAge(TimeSpan.FromDays(365));
            response.Cache.SetSlidingExpiration(true);
            //response.AddHeader("X-Powered-By","CMSAlpha");
            response.Headers.Remove("Cache-Control");
            response.AddHeader("Cache-Control","public,max-age=31536000");
            if (encodingsAccepted.Contains("br") || encodingsAccepted.Contains("brotli"))
            {
                response.Filter = new BrotliStream(response.Filter, System.IO.Compression.CompressionMode.Compress);
                response.Headers.Remove("Content-Encoding");
                response.AppendHeader("Content-Encoding", "br");
            }
            else if (encodingsAccepted.Contains("gzip"))
            {
                response.Headers.Remove("Content-Encoding");
                response.AppendHeader("Content-encoding", "gzip");
                response.Filter = new GZipStream(response.Filter, CompressionMode.Compress);
            }
            else if (encodingsAccepted.Contains("deflate"))
            {
                response.Headers.Remove("Content-Encoding");
                response.AppendHeader("Content-encoding", "deflate");
                response.Filter = new DeflateStream(response.Filter, CompressionMode.Compress);
            }

        }

       
    }
```

i am using the custom filter due to the response caching header, when i use yours this is what i am getting on a live project.
from chrome dev tools network doc header
HTTP/1.1 200 OK
Cache-Control: private
Content-Type: text/html; charset=utf-8
Content-Encoding: br
Vary: Accept-Encoding
Server: Microsoft-IIS/8.5
X-AspNetMvc-Version: 5.2

**Comment by Taritsyn** [comment]
HTTP headers like this should be added before writing to the stream.

```csharp
response.AppendHeader("Content-Encoding", "br");
```
In the WebMarkupMin this [is done as follows](https://github.com/Taritsyn/WebMarkupMin/blob/9dfd8230e45478f07520404884f8eace8225f585/src/WebMarkupMin.AspNet4.Common/HttpCompressionFilterStream.cs#L155).

Perhaps you should move this code to a separate filter:

```csharp
var response = filterContext.HttpContext.Response;
response.Cache.SetExpires(DateTime.Now.AddYears(1));
response.Cache.SetCacheability(HttpCacheability.Public);
response.Cache.SetMaxAge(TimeSpan.FromDays(365));
response.Cache.SetSlidingExpiration(true);
//response.AddHeader("X-Powered-By","CMSAlpha");
response.Headers.Remove("Cache-Control");
response.AddHeader("Cache-Control","public,max-age=31536000");
```

And compression can be delegated to the `CompressContent` filter. You can also write your own version of the `BrotliCompressor` and `BrotliCompressorFactory` classes that will use the System.IO.Compression.Brotli library (as a basis you can use the source code of the [WebMarkupMin.AspNet.Brotli](https://github.com/Taritsyn/WebMarkupMin/tree/master/src/WebMarkupMin.AspNet.Brotli) module).

**Comment by aloksharma1** [comment]
thanks, i will look into it and implement the same.

**Comment by aloksharma1** [comment]
ok, i have succesfully implemented this in a separate filter and its working ok. i am sharing the code here so others can use it if they have a similar issue to mine:

```
public class UserCachingAttribute : ActionFilterAttribute
    {
        public int durationDays = 365;
        public override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            var response = filterContext.HttpContext.Response;
            response.Cache.SetExpires(DateTime.Now.AddDays(durationDays));
            response.Cache.SetCacheability(HttpCacheability.Public);
            response.Cache.SetMaxAge(TimeSpan.FromDays(durationDays));
            response.Cache.SetSlidingExpiration(true);
            response.AddHeader("X-Powered-By","UltraWebz");
            response.Headers.Remove("Cache-Control");
            response.AddHeader("Cache-Control", $"public,max-age={TimeSpan.FromDays(durationDays)}");
            base.OnActionExecuting(filterContext);
        }
    }
```

usage:
```
[CompressContent]
[MinifyHtml]
[MinifyXml]     
[UserCaching(durationDays=365)]//durationDays can be left empty if no custom value is required
public async Task<ActionResult> ActionName(parms.. param){
//do something;
}
```

**Comment by Taritsyn** [comment]
Great!
