### ISSUE TITLE
Minification not working for pages with response code !=200

### ISSUE THREAD

**Issue by aloksharma1** [Taritsyn/WebMarkupMin#84]
Hello,
when i am using minification on 404 or other custom error pages, its totally ignored if i set 
`HttpContext.Response.StatusCode=404;`
you can check the live url here [ultrawebz](http://www.ultrawebz.com/Error/HttpError404/?message=Nothing-Found-on-This-Url)
```
[CompressContent]
    [MinifyHtml]
    [MinifyXml]
public ActionResult HttpError404(string message="")
        {
            //HttpContext.Response.StatusCode=404; minification works only after this commented
            ViewBag.msg = message;
            return View();          
        }
```
but commenting this code is bad practice for seo.
i am using webmarkupmin ver 2.5.7 (core) WebMarkupMin.AspNet4.Mvc 2.5.0

regards

**Comment by Taritsyn** [comment]
Hello, Alok!

It's not a mistake, it was really meant to be. Makes no sense to apply optimization to the pages that have a response status different from `200`. In some situations, this may lead to new errors.

**Comment by aloksharma1** [comment]
I guess then i will need to use minification from code calling instead of attribute in this case, since my use case is different. we have a specific route table & controller redirects for different use cases.

**Comment by Taritsyn** [comment]
You can write your own action filter in which you will work directly with an instance of the `HtmlMinifier` class from the [WebMarkupMin.Core](https://www.nuget.org/packages/WebMarkupMin.Core/) module.

**Comment by CumpsD** [comment]
Thanks for the hint to the filter, I will have a look. My 404 error pages need to be minified too

**Comment by CumpsD** [comment]
Would it not be an option to allow https://github.com/Taritsyn/WebMarkupMin/blob/9ef693b33047d7d90f6be2f4f5dda9661a9d1dd6/src/WebMarkupMin.AspNetCore1/BodyWrapperStreamBase.cs#L155 to be configured at own risk?

**Comment by Taritsyn** [comment]
Hello, David!

What's the point of minifying a 404 error pages? They are not cached.

**Comment by CumpsD** [comment]
Deal with HTML issues out of my control.

Not minified I have tags on separate lines, creating whitespace in the layout. Minified they are correct.

**Comment by Taritsyn** [comment]
> Not minified I have tags on separate lines, creating whitespace in the layout. Minified they are correct.

Have you tried assigning to the `WhitespaceMinificationMode` property a value equal to the `Safe`?

Basically, I can add a `SupportedHttpStatusCodes` configuration property to all modules (similar to the `SupportedHttpMethods` and `SupportedMediaTypes` properties).

**Comment by CumpsD** [comment]
> Have you tried assigning to the `WhitespaceMinificationMode` property a value equal to the `Safe`?

Not yet, but that would still only be for valid status codes 

> Basically, I can add a `SupportedHttpStatusCodes` configuration property to all modules (similar to the `SupportedHttpMethods` and `SupportedMediaTypes` properties).

This would be a great addition 👍

**Comment by CumpsD** [comment]
Do you want me to make a PR for this?

**Comment by Taritsyn** [comment]
Hello, David!

This feature affects a lot of modules, so I'm implementing it myself.

**Comment by CumpsD** [comment]
Ok, thanks!

**Comment by Taritsyn** [comment]
Hello, David!

Update a WebMarkupMin to version [2.10.0](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.10.0). Add the following setting to the `Startup.cs` file:

```csharp
services.AddWebMarkupMin(options =>
{
    …
})
    .AddHtmlMinification(options =>
    {
        …
        options.SupportedHttpStatusCodes = new HashSet<int> { 200, 404 };
    })
    …
    ;
```

Also, you need to move the call of `UseWebMarkupMin` method before calling the error handler.

**Comment by CumpsD** [comment]
Thanks! I will try it right now.

**Comment by CumpsD** [comment]
By the way, for readability you can use StatusCodes in the readme or something :)

```
                    options.SupportedHttpStatusCodes = new HashSet<int>
                    {
                        StatusCodes.Status200OK,
```

**Comment by CumpsD** [comment]
It works beautifully! 👍🏻 💯

**Comment by Taritsyn** [comment]
Great!
