### ISSUE TITLE
WebMarkupMin.NUglify drop in processing speed after update

### ISSUE THREAD

**Issue by CRACKISH** [Taritsyn/WebMarkupMin#85]
I use 

```
<PackageReference Include="WebMarkupMin.Core" Version="2.5.1" />
<PackageReference Include="WebMarkupMin.NUglify" Version="2.5.2" />
```
My parameters:
```
new NUglifyJsMinificationSettings {
	PreserveImportantComments = false,
	AmdSupport = true,
	EvalTreatment = EvalTreatment.MakeImmediateSafe,
	ConstStatementsMozilla = true
};
```

And i have more 1000 js files. And each file is processed in 3 milliseconds. But after upgrading to the next or last version, the file processing speed drops to 200 milliseconds. And the total file processing increases from 3 seconds to 3 minutes. This is critical for me.

**Comment by Taritsyn** [comment]
Hello, Andrii!

> And i have more 1000 js files.

Why process JS-files by using the WebMarkupMin library?

**Comment by CRACKISH** [comment]
> Hello, Andrii!
> 
> > And i have more 1000 js files.
> 
> Why process JS-files by using the WebMarkupMin library?

Hi.

This is service, which serving other web applications. We minify and then we bundle client's web application content.

**Comment by Taritsyn** [comment]
> This is service, which serving other web applications. We minify and then we bundle client's web application content.

WebMarkupMin should only be used to markup minification. For minification of JS- and CSS-files use the [NUglify](https://github.com/xoofx/NUglify) library directly.
