### ISSUE TITLE
 Encoding Problems between Windows and Linux Asp Net Core

### ISSUE THREAD

**Issue by germanyesid** [Taritsyn/WebMarkupMin#86]
When mediaTypeHeader.Encoding is null The default encoding is being selected using the `Encoding.GetEncoding (0)` method, but this can give problems in Aspnet Core depending on which operating system is used. 
For example on windows after registering `System.Text.Encoding.RegisterProvider (System.Text.CodePagesEncodingProvider.Instance);` the encoding returned by `Encoding.GetEncoding (0)` changes to **"windows-1252"** but in Linux it returns **"UTF-8"**. So it can cause inconsistencies from one OS to another as is my case. According to experience I have seen that most pages return `mediaTypeHeader.Encoding` as null, they are old pages that normally use **"windows-1252"** or **"ISO-8859-1"** encoding. 
I suggest to be able to pass the **default encoding** in the options when adding the Middleware (`AddWebMarkupMin ()`) to avoid inconsistency from one OS to another.

![image](https://user-images.githubusercontent.com/13043081/61020802-88e0c600-a364-11e9-9248-b97e62ee9211.png)

**Comment by Taritsyn** [comment]
Hello, German!

Try to explicitly specify the response encoding.

**Comment by germanyesid** [comment]
@Taritsyn  unfortunately I do not have full control over the http responses of my application, because the http responses I get from third party websites where not all establish the charset. I will try to pass a default charset when it is null, but it would be possible to define the default encoding from the middleware configuration.

**Comment by Taritsyn** [comment]
> ..., because the http responses I get from third party websites where not all establish the charset.

I did not understand this part of sentence.

**Comment by Taritsyn** [comment]
Just make your own middleware, which will run before the WebMarkupMin middleware and change the response encoding.

**Comment by germanyesid** [comment]
Sorry for my bad English, My application works as a proxy, where I must show content from other web pages to the user and modify them in some cases, due to this I do not have all the control over the coding of the content. Currently I have defined working with "Windows-1252" where the charset of the website response is null and I have had good results, but in Linux I am having problems because WebMarkupMin uses the default encoding that is UTF8.  I will try to pass a default charset when it is null in my middleware. Thank you so much for everything

**Comment by Taritsyn** [comment]
Hello, German!

This feature has been added to [version 2.6.0](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.6.0).

**Comment by germanyesid** [comment]
Thank you so much for everything
