### ISSUE TITLE
dotnet core 3 support

### ISSUE THREAD

**Issue by bshafiei-ir** [Taritsyn/WebMarkupMin#88]
I'm using dotnet core 3.preview6.
After upgrading dotnet core from version 2.2 to version 3, I get exception.
How can I resolve it?

@Taritsyn

**Comment by Taritsyn** [comment]
Hello, Bahman!

Which module do you use?

**Comment by bshafiei-ir** [comment]
I'm using last version.

dotnet add package WebMarkupMin.Core --version 2.5.8

**Comment by Taritsyn** [comment]
Give an example of the full error message with stack trace.

**Comment by bshafiei-ir** [comment]
You can create an sample project with dotnet core3.preview6.
And add WebMarkupMin in that.
So build project and see result.

**Comment by Taritsyn** [comment]
Probably I already [fixed this error](https://github.com/Taritsyn/WebMarkupMin/commit/5c72440d1edffa29c60e945758b2ee816f830e66). In the second part of next week I will publish new release with the WebMarkupMin.AspNetCore3 package.

**Comment by Taritsyn** [comment]
Hello, Bahman!

Try to replace the WebMarkupMin.AspNetCore2 package by the [WebMarkupMin.AspNetCore3](https://www.nuget.org/packages/WebMarkupMin.AspNetCore3/) package.

**Comment by bshafiei-ir** [comment]
Thanks.
I have tried to use it, But it had some conflicts with my codes, And caused for some errors.
Did you write your project in dotnetstandard2.1?

warning NU1701: Package 'FluentFTP 16.0.13' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.0'. This package may not be fully compatible with your project.

**Comment by Taritsyn** [comment]
> warning NU1701: Package **'FluentFTP 16.0.13'** was restored using...

The problem is in the FluentFTP package. Update it to a version that supports the .NET Standard.

**Comment by Taritsyn** [comment]
> Did you write your project in dotnetstandard2.1?

No, WebMarkupMin.AspNetCore3 library is targeted to `netcoreapp3.0` (just like the Microsoft.AspNetCore.App library). If this could be done in ASP.NET Core 3.0, then I would do it. So far everyone is doing this, but I will look for other solutions.

**Comment by bshafiei-ir** [comment]
Thanks.
It sounds that works right.
