### ISSUE TITLE
Html Minifier Removes Double/Single Quotes in Preloaded textarea element 

### ISSUE THREAD

**Issue by aloksharma1** [Taritsyn/WebMarkupMin#89]
Hello ,

when doing minification on pages with editable data, i am loosing " or ' quotes and text becomes messed up, this doesnt happen if i remove the minification from my mvc action.
`htmlMinificationSettings.PreservableAttributeList` i even tried this option with data like this:

`htmlMinificationSettings.PreservableAttributeList = "form[method=get i], input[type], [xmlns], \", \'";`

but it didnt worked, suggestions?

thanks for the help

**Comment by Taritsyn** [comment]
Hello, Alok!

> htmlMinificationSettings.PreservableAttributeList = "form[method=get i], input[type], [xmlns], \", \'";

This setting will not help. Better try the following setting:

```charp
htmlMinificationSettings.AttributeQuotesRemovalMode = HtmlAttributeQuotesRemovalMode.KeepQuotes;
```

All these settings are described in the [documentation](https://github.com/Taritsyn/WebMarkupMin/wiki/HTML-Minifier).

**Comment by Taritsyn** [comment]
Also read the [“Ignoring fragments of markup”](https://github.com/Taritsyn/WebMarkupMin/wiki/Ignoring-fragments-of-markup) section of documentation.
