### ISSUE TITLE
Byte order mark added after minification

### ISSUE THREAD

**Issue by BNyachogo** [Taritsyn/WebMarkupMin#91]
I'm getting a Byte order Mark after HTML minification while using the WebMarkupMin.AspNet4.Mvc latest version. I saw a referenced commit from a while back that should have addressed it but I still see the issue occurring.
The end result is that there's a whitespace line at the end of the html page:
![image](https://user-images.githubusercontent.com/42472572/62799882-ec6b2a00-baaf-11e9-881f-7de279b38749.png)

**Comment by Taritsyn** [comment]
Hello!

What version of the WebMarkupMin do you use?

**Comment by BNyachogo** [comment]
Hi, 
I'm using version 2.6.0

**Comment by Taritsyn** [comment]
Send me an HTML file for testing.

**Comment by Taritsyn** [comment]
Which ASP.NET extension do you use?

**Comment by BNyachogo** [comment]
I'm using the 4.X MVC extension. Sending the Html will be tough since we load a bunch of partials dynamically before the page is rendered.

**Comment by Taritsyn** [comment]
I need a version of HTML file before minification.

**Comment by Taritsyn** [comment]
In general, I need to reproduce this error somehow, because the removal of BOM is already implemented in the WebMarkupMin.

**Comment by BNyachogo** [comment]
Here's a sample html file
[test.txt](https://github.com/Taritsyn/WebMarkupMin/files/3487842/test.txt)

**Comment by Taritsyn** [comment]
When minifying this file, I did not get the BOM characters in output file. It is possible that you saved this file in the wrong encoding. 

Are you sure the problem is in the WebMarkupMin?

Send me minified HTML file, so that I can detect what type of the BOM symbols it contains.

**Comment by Taritsyn** [comment]
Try writing a test like [these unit tests](https://github.com/Taritsyn/WebMarkupMin/blob/332c7a7bc7d510f4c2e9e707b5faa496e47d983b/test/WebMarkupMin.Core.Test/Html/MinificationTests.cs#L20-L64).

**Comment by BNyachogo** [comment]
ok. I'll try that to see if I can narrow down the issue. These are the byte order marks I'm getting
![image](https://user-images.githubusercontent.com/42472572/62868855-93380c00-bce4-11e9-9377-19daea948842.png)

**Comment by Taritsyn** [comment]
I would like to have HTML files for testing.

**Comment by BNyachogo** [comment]
here you go
[testminified.txt](https://github.com/Taritsyn/WebMarkupMin/files/3492721/testminified.txt)

**Comment by Taritsyn** [comment]
The usual BOM.

Try to make a demo project.

**Comment by BNyachogo** [comment]
Ok. So I was using the global filter.config to minify content (mentioned in the last section of this page https://github.com/Taritsyn/WebMarkupMin/wiki/ASP.NET-4.X-MVC) but when I removed that and did the minification at controller level, the issue does not occur. For our application that should be sufficient.

**Comment by Taritsyn** [comment]
Most likely, this error is somehow related to child actions, but, unfortunately, I can’t reproduce it.
