### ISSUE TITLE
Can't minify html script templates.

### ISSUE THREAD

**Issue by bshafiei-ir** [Taritsyn/WebMarkupMin#93]
I have some script templates in my web pages.
But minifier can't minify them.

![image](https://user-images.githubusercontent.com/19801131/63638465-8977b680-c69d-11e9-88b4-bd8a1fd389e1.png)

**Comment by Taritsyn** [comment]
Hello, Bahman!

For this purpose, use the `ProcessableScriptTypeList` configuration property (see the [“HTML Minifier”](https://github.com/Taritsyn/WebMarkupMin/wiki/HTML-Minifier) section of documentation). But keep in mind that only minification of DOM-based templates is supported.

**Comment by bshafiei-ir** [comment]
Thanks. ✔🙏
