### ISSUE TITLE
<code> tag and removal of spaces

### ISSUE THREAD

**Issue by Sausbolle** [Taritsyn/WebMarkupMin#95]
WebMarkupMin concats multipe spaces inside `<code>`  tags to one space.
Often (I would say always) the excact spacing inside `<code>` tags is of importance.
So I would want the WebMarkupMin to not change the formatting inside `<code>` tags.

**Comment by Taritsyn** [comment]
Hello!

> Often (I would say always) the excact spacing inside &lt;code&gt; tags is of importance.

It is possible that you need to use the `pre` tag.

You can also wrap the `code` tag in a ignoring comment tag (see the [“Ignoring fragments of markup”](https://github.com/Taritsyn/WebMarkupMin/wiki/Ignoring-fragments-of-markup) section of documentation).

**Comment by Sausbolle** [comment]
Thank you worked like a charm :)
