### ISSUE TITLE
HTML entity quotes breaks minification

### ISSUE THREAD

**Issue by sampotts** [Taritsyn/WebMarkupMin#96]
As far as I can tell, this is valid HTML:

```html
<meta name="description" property="og:description" content="This is a &quot;test&quot; of the meta description to break minification.">
```

Although, this throws an error:

`In the start tag <meta> found invalid characters.`

**Comment by Taritsyn** [comment]
Hello, Sam!

I have this example of code does not give an error. You can check it on the [WebMarkupMin Online site](http://webmarkupmin.apphb.com/minifiers/html-minifier).

**Comment by sampotts** [comment]
It must be a configuration option then. We're only setting `RemoveHtmlComments` to false. I'll take another look then. It's odd because a page that fails to minify using the C# library (throwing that error), works fine in that demo page. 

This is our code:

```csharp
// Minify HTML
var minifier = new HtmlMinifier(new HtmlMinificationSettings
{
    RemoveHtmlComments = false
});

var result = minifier.Minify(content, false);

return result.Errors.Count == 0 ? result.MinifiedContent : content;
```

**Comment by sampotts** [comment]
I found the issue. It was somewhere else in the file. Sorry!
