### ISSUE TITLE
asp.net core 3.0 rc1 issue

### ISSUE THREAD

**Issue by dotnetshadow** [Taritsyn/WebMarkupMin#97]
Hi there,

Firstly great work with this project.
I just tried the latest version **2.6.3-rc1** and got the following error

```cs
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'WebMarkupMin.AspNetCore3, Version=2.6.3.0, Culture=neutral, PublicKeyToken=99472178d266584b'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'WebMarkupMin.AspNetCore3, Version=2.6.3.0, Culture=neutral, PublicKeyToken=99472178d266584b'
```

**2.6.2-preview3** works fine

I'm not sure why it's happening, seems all you changed was the version number

**Comment by Taritsyn** [comment]
Hello!

Just `WebMarkupMin.AspNetCore3.dll` assembly not found. Try reinstalling NuGet package.

**Comment by dotnetshadow** [comment]
@Taritsyn I did try that and I can see that nuget does have the files 

![image](https://user-images.githubusercontent.com/296247/65143062-6b606480-da57-11e9-9853-85af7ae75a97.png)

It restores and it builds, but when I run my app it fails

**Comment by Taritsyn** [comment]
I tried to make a project from scratch and everything works for me. Try clearing the `bin ' directory and rebuilding a project.

**Comment by dotnetshadow** [comment]
@Taritsyn Awesome thank you, that worked, so sorry not sure what happened there. Clearing the bin directory fixed the issue

**Comment by Taritsyn** [comment]
We work with preview version of Visual Studio, so such errors can occur for everyone.
